In [1]:
!gdown 10abEfTSrWVzR6D24mdhbwACf3LDYltY7

Downloading...
From: https://drive.google.com/uc?id=10abEfTSrWVzR6D24mdhbwACf3LDYltY7
To: /content/Fish.csv
100% 6.47k/6.47k [00:00<00:00, 15.9MB/s]

In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

#1.Load Data

In [4]:
df = pd.read_csv('./Fish.csv')
df

    Species  Weight  VerticalLen  DiagonalLen  CrossLen   Height   Width
0     Bream   242.0         23.2         25.4      30.0  11.5200  4.0200
1     Bream   290.0         24.0         26.3      31.2  12.4800  4.3056
2     Bream   340.0         23.9         26.5      31.1  12.3778  4.6961
3     Bream   363.0         26.3         29.0      33.5  12.7300  4.4555
4     Bream   430.0         26.5         29.0      34.0  12.4440  5.1340
..      ...     ...          ...          ...       ...      ...     ...
154   Smelt    12.2         11.5         12.2      13.4   2.0904  1.3936
155   Smelt    13.4         11.7         12.4      13.5   2.4300  1.2690
156   Smelt    12.2         12.1         13.0      13.8   2.2770  1.2558
157   Smelt    19.7         13.2         14.3      15.2   2.8728  2.0672
158   Smelt    19.9         13.8         15.0      16.2   2.9322  1.8792

[159 rows x 7 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Species      159 non-null    object
 1   Weight       159 non-null    float64
 2   VerticalLen  159 non-null    float64
 3   DiagonalLen  159 non-null    float64
 4   CrossLen     159 non-null    float64
 5   Height       159 non-null    float64
 6   Width        159 non-null    float64
dtypes: float64(6), object(1)
memory usage: 8.8+ KB

**One hot encoding**

In [8]:
df

    Species  Weight  VerticalLen  DiagonalLen  CrossLen   Height   Width
0     Bream   242.0         23.2         25.4      30.0  11.5200  4.0200
1     Bream   290.0         24.0         26.3      31.2  12.4800  4.3056
2     Bream   340.0         23.9         26.5      31.1  12.3778  4.6961
3     Bream   363.0         26.3         29.0      33.5  12.7300  4.4555
4     Bream   430.0         26.5         29.0      34.0  12.4440  5.1340
..      ...     ...          ...          ...       ...      ...     ...
154   Smelt    12.2         11.5         12.2      13.4   2.0904  1.3936
155   Smelt    13.4         11.7         12.4      13.5   2.4300  1.2690
156   Smelt    12.2         12.1         13.0      13.8   2.2770  1.2558
157   Smelt    19.7         13.2         14.3      15.2   2.8728  2.0672
158   Smelt    19.9         13.8         15.0      16.2   2.9322  1.8792

[159 rows x 7 columns]

In [9]:
encode_species = pd.get_dummies(df.Species)
encode_species.head(5)

   Bream  Parkki  Perch   Pike  Roach  Smelt  Whitefish
0   True   False  False  False  False  False      False
1   True   False  False  False  False  False      False
2   True   False  False  False  False  False      False
3   True   False  False  False  False  False      False
4   True   False  False  False  False  False      False

**Label Encoding**

In [10]:
df["Species"] = df["Species"].astype('category')
label_ecnoding_species = df["Species"].cat.codes
label_ecnoding_species

0      0
1      0
2      0
3      0
4      0
      ..
154    5
155    5
156    5
157    5
158    5
Length: 159, dtype: int8

In [11]:
new_df = pd.concat([df, encode_species], axis='columns')
new_df

,Species,Weight,VerticalLen,DiagonalLen,CrossLen,Height,Width,Bream,Parkki,Perch,Pike,Roach,Smelt,Whitefish
0,Bream,242.0,23.2,25.4,30.0,11.5200,4.0200,True,False,False,False,False,False,False
1,Bream,290.0,24.0,26.3,31.2,12.4800,4.3056,True,False,False,False,False,False,False
2,Bream,340.0,23.9,26.5,31.1,12.3778,4.6961,True,False,False,False,False,False,False
3,Bream,363.0,26.3,29.0,33.5,12.7300,4.4555,True,False,False,False,False,False,False
4,Bream,430.0,26.5,29.0,34.0,12.4440,5.1340,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,Smelt,12.2,11.5,12.2,13.4,2.0904,1.3936,False,False,False,False,False,True,False
155,Smelt,13.4,11.7,12.4,13.5,2.4300,1.2690,False,False,False,False,False,True,False
156,Smelt,12.2,12.1,13.0,13.8,2.2770,1.2558,False,False,False,False,False,True,False
157,Smelt,19.7,13.2,14.3,15.2,2.8728,2.0672,False,False,False,False,False,True,False
158,Smelt,19.9,13.8,15.0,16.2,2.9322,1.8792,False,False,False,False,False,True,False

In [12]:
X = new_df[[
    'VerticalLen', 'DiagonalLen', 'CrossLen', 'Height', 'Width',
    'Bream', 'Parkki', 'Perch', 'Pike', 'Roach', 'Smelt', 'Whitefish'
]]
y = new_df['Weight']

In [13]:
X = X.values
y = y.values

In [14]:
X

array([[23.2, 25.4, 30.0, ..., False, False, False],
       [24.0, 26.3, 31.2, ..., False, False, False],
       [23.9, 26.5, 31.1, ..., False, False, False],
       ...,
       [12.1, 13.0, 13.8, ..., False, True, False],
       [13.2, 14.3, 15.2, ..., False, True, False],
       [13.8, 15.0, 16.2, ..., False, True, False]], dtype=object)

In [15]:
X_data = np.hstack((np.ones((X.shape[0], 1)), X))
X_data

array([[1.0, 23.2, 25.4, ..., False, False, False],
       [1.0, 24.0, 26.3, ..., False, False, False],
       [1.0, 23.9, 26.5, ..., False, False, False],
       ...,
       [1.0, 12.1, 13.0, ..., False, True, False],
       [1.0, 13.2, 14.3, ..., False, True, False],
       [1.0, 13.8, 15.0, ..., False, True, False]], dtype=object)

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X_data, y, test_size=0.2, random_state=42)
print('X_train shape: ', X_train.shape)
print('X_test shape: ', X_test.shape)
print('y_train shape: ', y_train.shape)
print('y_train shape: ', y_test.shape)

X_train shape:  (127, 13)
X_test shape:  (32, 13)
y_train shape:  (127,)
y_train shape:  (32,)

#Linear Regression

In [17]:
def r2score(y_pred, y):
    rss = np.sum((y_pred - y) ** 2)
    tss = np.sum((y-y.mean()) ** 2)

    r2 = 1 - (rss / tss)
    return r2

In [18]:
class LinearRegression:
    def __init__(self, X_data, y_target, learning_rate=0.00001, num_epochs=10000):
        self.X_data = X_data
        self.y_target = y_target
        self.learning_rate = learning_rate
        self.num_epochs = num_epochs
        self.num_samples = self.X_data.shape[0]

        # Initial Coefficients
        self.theta = np.random.randn(self.X_data.shape[1])
        self.losses = []

    def compute_loss(self, y_pred, y_target):
        loss = (y_pred-y_target)*(y_pred-y_target)
        loss = np.mean(loss)
        return loss

    def predict(self, X_data):
        y_pred = X_data.dot(self.theta)
        return y_pred

    def fit(self):
        for epoch in range(self.num_epochs):
            # predict
            y_pred = self.predict(self.X_data)

            # compute loss
            loss = self.compute_loss(y_pred, self.y_target)
            self.losses.append(loss)

            # compute gradient
            k = 2*(y_pred-self.y_target)
            gradients = self.X_data.T.dot(k)/self.num_samples

            # update weight
            self.theta = self.theta - self.learning_rate*gradients

            print(f'Epoch: {epoch} - Loss: {loss}')

        return {
            'loss': sum(self.losses)/len(self.losses),
            'weight': self.theta
        }

In [19]:
linear_model = LinearRegression(X_train, y_train, learning_rate=0.00001, num_epochs=1000)
linear_model.fit()

Epoch: 0 - Loss: 226436.44783030206
Epoch: 1 - Loss: 206095.5832031268
Epoch: 2 - Loss: 188054.78354620922
Epoch: 3 - Loss: 172053.9633937767
Epoch: 4 - Loss: 157862.4470795469
Epoch: 5 - Loss: 145275.64315179436
Epoch: 6 - Loss: 134112.09483706168
Epoch: 7 - Loss: 124210.86402988921
Epoch: 8 - Loss: 115429.21109430096
Epoch: 9 - Loss: 107640.53702740379
Epoch: 10 - Loss: 100732.55831786695
Epoch: 11 - Loss: 94605.68818673713
Epoch: 12 - Loss: 89171.60087340449
Epoch: 13 - Loss: 84351.9582684398
Epoch: 14 - Loss: 80077.28053553517
Epoch: 15 - Loss: 76285.94444062826
Epoch: 16 - Loss: 72923.2949474078
Epoch: 17 - Loss: 69940.85727132803
Epoch: 18 - Loss: 67295.63803254049
Epoch: 19 - Loss: 64949.505432665595
Epoch: 20 - Loss: 62868.63951959015
Epoch: 21 - Loss: 61023.04461491603
Epoch: 22 - Loss: 59386.116874865904
Epoch: 23 - Loss: 57934.260750296955
Epoch: 24 - Loss: 56646.54881643492
Epoch: 25 - Loss: 55504.42006819224
Epoch: 26 - Loss: 54491.412331480205
Epoch: 27 - Loss: 53592.92493276628
Epoch: 28 - Loss: 52796.008205349965
Epoch: 29 - Loss: 52089.17679773215
Epoch: 30 - Loss: 51462.2440925956
Epoch: 31 - Loss: 50906.175349264486
Epoch: 32 - Loss: 50412.95745243872
Epoch: 33 - Loss: 49975.4833894086
Epoch: 34 - Loss: 49587.4497902906
Epoch: 35 - Loss: 49243.266054151296
Epoch: 36 - Loss: 48937.97375091687
Epoch: 37 - Loss: 48667.175137108614
Epoch: 38 - Loss: 48426.96975483641
Epoch: 39 - Loss: 48213.89820001553
Epoch: 40 - Loss: 48024.89224913042
Epoch: 41 - Loss: 47857.23062553577
Epoch: 42 - Loss: 47708.4997675916
Epoch: 43 - Loss: 47576.55903303719
Epoch: 44 - Loss: 47459.50983796552
Epoch: 45 - Loss: 47355.66828548352
Epoch: 46 - Loss: 47263.540889453376
Epoch: 47 - Loss: 47181.803043331194
Epoch: 48 - Loss: 47109.27992369427
Epoch: 49 - Loss: 47044.92955314879
Epoch: 50 - Loss: 46987.82777844055
Epoch: 51 - Loss: 46937.15494720233
Epoch: 52 - Loss: 46892.18409126091
Epoch: 53 - Loss: 46852.27044614552
Epoch: 54 - Loss: 46816.84215570297
Epoch: 55 - Loss: 46785.39202781185
Epoch: 56 - Loss: 46757.47022233907
Epoch: 57 - Loss: 46732.67776592349
Epoch: 58 - Loss: 46710.660800091624
Epoch: 59 - Loss: 46691.105479781334
Epoch: 60 - Loss: 46673.733448727784
Epoch: 61 - Loss: 46658.297826480564
Epoch: 62 - Loss: 46644.57964919959
Epoch: 63 - Loss: 46632.38471291586
Epoch: 64 - Loss: 46621.540773748544
Epoch: 65 - Loss: 46611.89506471452
Epoch: 66 - Loss: 46603.31209333042
Epoch: 67 - Loss: 46595.671688256545
Epoch: 68 - Loss: 46588.86726682089
Epoch: 69 - Loss: 46582.8042984475
Epoch: 70 - Loss: 46577.398941836225
Epoch: 71 - Loss: 46572.57683624672
Epoch: 72 - Loss: 46568.27202946102
Epoch: 73 - Loss: 46564.42602696927
Epoch: 74 - Loss: 46560.98694867126
Epoch: 75 - Loss: 46557.90878093575
Epoch: 76 - Loss: 46555.15071323527
Epoch: 77 - Loss: 46552.67654979246
Epoch: 78 - Loss: 46550.454187755786
Epoch: 79 - Loss: 46548.4551543822
Epoch: 80 - Loss: 46546.654196553434
Epoch: 81 - Loss: 46545.02891670933
Epoch: 82 - Loss: 46543.55944994854
Epoch: 83 - Loss: 46542.22817764187
Epoch: 84 - Loss: 46541.01947342965
Epoch: 85 - Loss: 46539.91947794105
Epoch: 86 - Loss: 46538.915898987325
Epoch: 87 - Loss: 46537.997834349
Epoch: 88 - Loss: 46537.15561460165
Epoch: 89 - Loss: 46536.3806637147
Epoch: 90 - Loss: 46535.66537541302
Epoch: 91 - Loss: 46535.00300351965
Epoch: 92 - Loss: 46534.387564698016
Epoch: 93 - Loss: 46533.813752192
Epoch: 94 - Loss: 46533.27685931969
Epoch: 95 - Loss: 46532.772711618825
Epoch: 96 - Loss: 46532.297606664644
Epoch: 97 - Loss: 46531.84826069296
Epoch: 98 - Loss: 46531.42176125932
Epoch: 99 - Loss: 46531.015525250885
Epoch: 100 - Loss: 46530.62726164674
Epoch: 101 - Loss: 46530.2549384886
Epoch: 102 - Loss: 46529.89675358679
Epoch: 103 - Loss: 46529.551108538646
Epoch: 104 - Loss: 46529.21658568478
Epoch: 105 - Loss: 46528.89192767101
Epoch: 106 - Loss: 46528.5760193215
Epoch: 107 - Loss: 46528.267871561686
Epoch: 108 - Loss: 46527.96660715896
Epoch: 109 - Loss: 46527.67144807584
Epoch: 110 - Loss: 46527.381704253356
Epoch: 111 - Loss: 46527.096763662594
Epoch: 112 - Loss: 46526.81608348132
Epoch: 113 - Loss: 46526.5391822681
Epoch: 114 - Loss: 46526.26563302171
Epoch: 115 - Loss: 46525.99505702511
Epoch: 116 - Loss: 46525.72711838551
Epoch: 117 - Loss: 46525.46151919205
Epoch: 118 - Loss: 46525.1979952208
Epoch: 119 - Loss: 46524.93631212558
Epoch: 120 - Loss: 46524.67626205937
Epoch: 121 - Loss: 46524.417660678046
Epoch: 122 - Loss: 46524.16034448251
Epoch: 123 - Loss: 46523.90416846174
Epoch: 124 - Loss: 46523.64900400217
Epoch: 125 - Loss: 46523.394737033355
Epoch: 126 - Loss: 46523.14126638382
Epoch: 127 - Loss: 46522.888502322094
Epoch: 128 - Loss: 46522.63636526338
Epoch: 129 - Loss: 46522.384784622074
Epoch: 130 - Loss: 46522.133697794074
Epoch: 131 - Loss: 46521.883049254495
Epoch: 132 - Loss: 46521.63278975692
Epoch: 133 - Loss: 46521.382875623654
Epoch: 134 - Loss: 46521.133268115846
Epoch: 135 - Loss: 46520.88393287513
Epoch: 136 - Loss: 46520.634839428254
Epoch: 137 - Loss: 46520.385960747844
Epoch: 138 - Loss: 46520.13727286254
Epoch: 139 - Loss: 46519.888754511616
Epoch: 140 - Loss: 46519.64038683848
Epoch: 141 - Loss: 46519.39215311877
Epoch: 142 - Loss: 46519.144038519036
Epoch: 143 - Loss: 46518.89602988341
Epoch: 144 - Loss: 46518.64811554347
Epoch: 145 - Loss: 46518.40028515012
Epoch: 146 - Loss: 46518.15252952462
Epoch: 147 - Loss: 46517.90484052605
Epoch: 148 - Loss: 46517.65721093394
Epoch: 149 - Loss: 46517.40963434437
Epoch: 150 - Loss: 46517.162105077514
Epoch: 151 - Loss: 46516.914618095674
Epoch: 152 - Loss: 46516.66716893086
Epoch: 153 - Loss: 46516.419753620205
Epoch: 154 - Loss: 46516.17236864903
Epoch: 155 - Loss: 46515.92501089985
Epoch: 156 - Loss: 46515.67767760787
Epoch: 157 - Loss: 46515.43036632082
Epoch: 158 - Loss: 46515.18307486365
Epoch: 159 - Loss: 46514.93580130725
Epoch: 160 - Loss: 46514.68854394069
Epoch: 161 - Loss: 46514.44130124633
Epoch: 162 - Loss: 46514.194071878184
Epoch: 163 - Loss: 46513.946854642454
Epoch: 164 - Loss: 46513.69964848026
Epoch: 165 - Loss: 46513.45245245246
Epoch: 166 - Loss: 46513.20526572604
Epoch: 167 - Loss: 46512.958087562125
Epoch: 168 - Loss: 46512.71091730542
Epoch: 169 - Loss: 46512.4637543746
Epoch: 170 - Loss: 46512.216598254156
Epoch: 171 - Loss: 46511.96944848673
Epoch: 172 - Loss: 46511.72230466675
Epoch: 173 - Loss: 46511.475166434386
Epoch: 174 - Loss: 46511.228033470434
Epoch: 175 - Loss: 46510.9809054919
Epoch: 176 - Loss: 46510.73378224761
Epoch: 177 - Loss: 46510.486663514814
Epoch: 178 - Loss: 46510.23954909589
Epoch: 179 - Loss: 46509.99243881557
Epoch: 180 - Loss: 46509.74533251835
Epoch: 181 - Loss: 46509.49823006623
Epoch: 182 - Loss: 46509.251131336896
Epoch: 183 - Loss: 46509.00403622168
Epoch: 184 - Loss: 46508.75694462431
Epoch: 185 - Loss: 46508.509856459204
Epoch: 186 - Loss: 46508.262771650625
Epoch: 187 - Loss: 46508.015690131215
Epoch: 188 - Loss: 46507.76861184118
Epoch: 189 - Loss: 46507.52153672759
Epoch: 190 - Loss: 46507.27446474336
Epoch: 191 - Loss: 46507.02739584672
Epoch: 192 - Loss: 46506.780330000605
Epoch: 193 - Loss: 46506.5332671721
Epoch: 194 - Loss: 46506.28620733191
Epoch: 195 - Loss: 46506.039150454126
Epoch: 196 - Loss: 46505.79209651571
Epoch: 197 - Loss: 46505.54504549615
Epoch: 198 - Loss: 46505.29799737718
Epoch: 199 - Loss: 46505.050952142716
Epoch: 200 - Loss: 46504.80390977835
Epoch: 201 - Loss: 46504.5568702712
Epoch: 202 - Loss: 46504.30983360997
Epoch: 203 - Loss: 46504.06279978448
Epoch: 204 - Loss: 46503.81576878578
Epoch: 205 - Loss: 46503.56874060579
Epoch: 206 - Loss: 46503.321715237325
Epoch: 207 - Loss: 46503.07469267406
Epoch: 208 - Loss: 46502.827672910265
Epoch: 209 - Loss: 46502.58065594087
Epoch: 210 - Loss: 46502.333641761295
Epoch: 211 - Loss: 46502.08663036751
Epoch: 212 - Loss: 46501.839621755826
Epoch: 213 - Loss: 46501.592615923044
Epoch: 214 - Loss: 46501.3456128662
Epoch: 215 - Loss: 46501.09861258263
Epoch: 216 - Loss: 46500.85161507002
Epoch: 217 - Loss: 46500.604620326216
Epoch: 218 - Loss: 46500.35762834929
Epoch: 219 - Loss: 46500.11063913743
Epoch: 220 - Loss: 46499.86365268924
Epoch: 221 - Loss: 46499.61666900305
Epoch: 222 - Loss: 46499.36968807768
Epoch: 223 - Loss: 46499.12270991198
Epoch: 224 - Loss: 46498.875734504705
Epoch: 225 - Loss: 46498.62876185502
Epoch: 226 - Loss: 46498.38179196188
Epoch: 227 - Loss: 46498.13482482446
Epoch: 228 - Loss: 46497.88786044198
Epoch: 229 - Loss: 46497.6408988137
Epoch: 230 - Loss: 46497.393939938964
Epoch: 231 - Loss: 46497.14698381704
Epoch: 232 - Loss: 46496.90003044737
Epoch: 233 - Loss: 46496.65307982941
Epoch: 234 - Loss: 46496.40613196261
Epoch: 235 - Loss: 46496.159186846424
Epoch: 236 - Loss: 46495.912244480365
Epoch: 237 - Loss: 46495.665304864066
Epoch: 238 - Loss: 46495.418367996885
Epoch: 239 - Loss: 46495.17143387858
Epoch: 240 - Loss: 46494.924502508635
Epoch: 241 - Loss: 46494.67757388661
Epoch: 242 - Loss: 46494.43064801223
Epoch: 243 - Loss: 46494.18372488502
Epoch: 244 - Loss: 46493.93680450466
Epoch: 245 - Loss: 46493.68988687071
Epoch: 246 - Loss: 46493.442971982906
Epoch: 247 - Loss: 46493.1960598408
Epoch: 248 - Loss: 46492.94915044413
Epoch: 249 - Loss: 46492.702243792555
Epoch: 250 - Loss: 46492.455339885666
Epoch: 251 - Loss: 46492.2084387232
Epoch: 252 - Loss: 46491.96154030478
Epoch: 253 - Loss: 46491.71464463009
Epoch: 254 - Loss: 46491.46775169883
Epoch: 255 - Loss: 46491.22086151075
Epoch: 256 - Loss: 46490.973974065375
Epoch: 257 - Loss: 46490.727089362466
Epoch: 258 - Loss: 46490.480207401815
Epoch: 259 - Loss: 46490.23332818289
Epoch: 260 - Loss: 46489.98645170557
Epoch: 261 - Loss: 46489.739577969434
Epoch: 262 - Loss: 46489.4927069743
Epoch: 263 - Loss: 46489.24583871972
Epoch: 264 - Loss: 46488.99897320546
Epoch: 265 - Loss: 46488.7521104312
Epoch: 266 - Loss: 46488.505250396636
Epoch: 267 - Loss: 46488.258393101496
Epoch: 268 - Loss: 46488.01153854543
Epoch: 269 - Loss: 46487.76468672818
Epoch: 270 - Loss: 46487.5178376494
Epoch: 271 - Loss: 46487.27099130882
Epoch: 272 - Loss: 46487.024147706135
Epoch: 273 - Loss: 46486.77730684099
Epoch: 274 - Loss: 46486.53046871321
Epoch: 275 - Loss: 46486.2836333224
Epoch: 276 - Loss: 46486.036800668284
Epoch: 277 - Loss: 46485.78997075055
Epoch: 278 - Loss: 46485.54314356887
Epoch: 279 - Loss: 46485.296319123045
Epoch: 280 - Loss: 46485.04949741269
Epoch: 281 - Loss: 46484.802678437554
Epoch: 282 - Loss: 46484.555862197325
Epoch: 283 - Loss: 46484.30904869167
Epoch: 284 - Loss: 46484.06223792038
Epoch: 285 - Loss: 46483.81542988303
Epoch: 286 - Loss: 46483.56862457942
Epoch: 287 - Loss: 46483.32182200926
Epoch: 288 - Loss: 46483.07502217218
Epoch: 289 - Loss: 46482.82822506797
Epoch: 290 - Loss: 46482.581430696235
Epoch: 291 - Loss: 46482.33463905679
Epoch: 292 - Loss: 46482.08785014924
Epoch: 293 - Loss: 46481.841063973356
Epoch: 294 - Loss: 46481.5942805288
Epoch: 295 - Loss: 46481.3474998153
Epoch: 296 - Loss: 46481.10072183257
Epoch: 297 - Loss: 46480.85394658028
Epoch: 298 - Loss: 46480.607174058176
Epoch: 299 - Loss: 46480.36040426594
Epoch: 300 - Loss: 46480.11363720327
Epoch: 301 - Loss: 46479.86687286988
Epoch: 302 - Loss: 46479.62011126543
Epoch: 303 - Loss: 46479.37335238971
Epoch: 304 - Loss: 46479.12659624241
Epoch: 305 - Loss: 46478.87984282319
Epoch: 306 - Loss: 46478.63309213179
Epoch: 307 - Loss: 46478.38634416788
Epoch: 308 - Loss: 46478.13959893125
Epoch: 309 - Loss: 46477.89285642153
Epoch: 310 - Loss: 46477.646116638396
Epoch: 311 - Loss: 46477.39937958164
Epoch: 312 - Loss: 46477.152645250935
Epoch: 313 - Loss: 46476.90591364597
Epoch: 314 - Loss: 46476.65918476646
Epoch: 315 - Loss: 46476.41245861211
Epoch: 316 - Loss: 46476.165735182694
Epoch: 317 - Loss: 46475.91901447785
Epoch: 318 - Loss: 46475.672296497236
Epoch: 319 - Loss: 46475.42558124063
Epoch: 320 - Loss: 46475.178868707786
Epoch: 321 - Loss: 46474.93215889832
Epoch: 322 - Loss: 46474.68545181198
Epoch: 323 - Loss: 46474.43874744845
Epoch: 324 - Loss: 46474.19204580748
Epoch: 325 - Loss: 46473.94534688876
Epoch: 326 - Loss: 46473.69865069196
Epoch: 327 - Loss: 46473.45195721684
Epoch: 328 - Loss: 46473.20526646314
Epoch: 329 - Loss: 46472.95857843045
Epoch: 330 - Loss: 46472.71189311858
Epoch: 331 - Loss: 46472.46521052721
Epoch: 332 - Loss: 46472.21853065604
Epoch: 333 - Loss: 46471.97185350479
Epoch: 334 - Loss: 46471.72517907317
Epoch: 335 - Loss: 46471.47850736089
Epoch: 336 - Loss: 46471.23183836759
Epoch: 337 - Loss: 46470.98517209309
Epoch: 338 - Loss: 46470.738508537084
Epoch: 339 - Loss: 46470.4918476992
Epoch: 340 - Loss: 46470.24518957926
Epoch: 341 - Loss: 46469.99853417686
Epoch: 342 - Loss: 46469.751881491786
Epoch: 343 - Loss: 46469.50523152372
Epoch: 344 - Loss: 46469.25858427238
Epoch: 345 - Loss: 46469.0119397375
Epoch: 346 - Loss: 46468.76529791873
Epoch: 347 - Loss: 46468.51865881581
Epoch: 348 - Loss: 46468.27202242851
Epoch: 349 - Loss: 46468.025388756425
Epoch: 350 - Loss: 46467.77875779938
Epoch: 351 - Loss: 46467.53212955696
Epoch: 352 - Loss: 46467.28550402907
Epoch: 353 - Loss: 46467.03888121518
Epoch: 354 - Loss: 46466.792261115246
Epoch: 355 - Loss: 46466.54564372877
Epoch: 356 - Loss: 46466.299029055604
Epoch: 357 - Loss: 46466.05241709538
Epoch: 358 - Loss: 46465.80580784786
Epoch: 359 - Loss: 46465.55920131268
Epoch: 360 - Loss: 46465.312597489676
Epoch: 361 - Loss: 46465.065996378486
Epoch: 362 - Loss: 46464.8193979788
Epoch: 363 - Loss: 46464.572802290364
Epoch: 364 - Loss: 46464.326209312916
Epoch: 365 - Loss: 46464.079619046104
Epoch: 366 - Loss: 46463.83303148968
Epoch: 367 - Loss: 46463.58644664336
Epoch: 368 - Loss: 46463.33986450683
Epoch: 369 - Loss: 46463.09328507988
Epoch: 370 - Loss: 46462.84670836213
Epoch: 371 - Loss: 46462.60013435335
Epoch: 372 - Loss: 46462.353563053206
Epoch: 373 - Loss: 46462.10699446144
Epoch: 374 - Loss: 46461.860428577806
Epoch: 375 - Loss: 46461.61386540193
Epoch: 376 - Loss: 46461.367304933585
Epoch: 377 - Loss: 46461.12074717249
Epoch: 378 - Loss: 46460.87419211837
Epoch: 379 - Loss: 46460.62763977085
Epoch: 380 - Loss: 46460.38109012974
Epoch: 381 - Loss: 46460.13454319472
Epoch: 382 - Loss: 46459.88799896552
Epoch: 383 - Loss: 46459.641457441845
Epoch: 384 - Loss: 46459.39491862338
Epoch: 385 - Loss: 46459.14838250991
Epoch: 386 - Loss: 46458.90184910107
Epoch: 387 - Loss: 46458.65531839662
Epoch: 388 - Loss: 46458.40879039631
Epoch: 389 - Loss: 46458.162265099796
Epoch: 390 - Loss: 46457.91574250679
Epoch: 391 - Loss: 46457.66922261703
Epoch: 392 - Loss: 46457.42270543027
Epoch: 393 - Loss: 46457.17619094612
Epoch: 394 - Loss: 46456.929679164445
Epoch: 395 - Loss: 46456.68317008483
Epoch: 396 - Loss: 46456.436663707034
Epoch: 397 - Loss: 46456.19016003082
Epoch: 398 - Loss: 46455.94365905583
Epoch: 399 - Loss: 46455.69716078186
Epoch: 400 - Loss: 46455.45066520859
Epoch: 401 - Loss: 46455.204172335696
Epoch: 402 - Loss: 46454.957682162916
Epoch: 403 - Loss: 46454.71119469001
Epoch: 404 - Loss: 46454.46470991667
Epoch: 405 - Loss: 46454.21822784261
Epoch: 406 - Loss: 46453.97174846751
Epoch: 407 - Loss: 46453.725271791176
Epoch: 408 - Loss: 46453.47879781327
Epoch: 409 - Loss: 46453.232326533514
Epoch: 410 - Loss: 46452.98585795158
Epoch: 411 - Loss: 46452.73939206727
Epoch: 412 - Loss: 46452.492928880296
Epoch: 413 - Loss: 46452.246468390316
Epoch: 414 - Loss: 46452.00001059708
Epoch: 415 - Loss: 46451.75355550029
Epoch: 416 - Loss: 46451.50710309971
Epoch: 417 - Loss: 46451.260653395024
Epoch: 418 - Loss: 46451.014206385975
Epoch: 419 - Loss: 46450.76776207219
Epoch: 420 - Loss: 46450.52132045355
Epoch: 421 - Loss: 46450.27488152963
Epoch: 422 - Loss: 46450.02844530022
Epoch: 423 - Loss: 46449.78201176502
Epoch: 424 - Loss: 46449.53558092376
Epoch: 425 - Loss: 46449.28915277614
Epoch: 426 - Loss: 46449.0427273219
Epoch: 427 - Loss: 46448.796304560754
Epoch: 428 - Loss: 46448.549884492415
Epoch: 429 - Loss: 46448.30346711665
Epoch: 430 - Loss: 46448.0570524331
Epoch: 431 - Loss: 46447.8106404415
Epoch: 432 - Loss: 46447.56423114164
Epoch: 433 - Loss: 46447.317824533195
Epoch: 434 - Loss: 46447.071420615845
Epoch: 435 - Loss: 46446.82501938939
Epoch: 436 - Loss: 46446.5786208535
Epoch: 437 - Loss: 46446.332225007936
Epoch: 438 - Loss: 46446.08583185237
Epoch: 439 - Loss: 46445.83944138654
Epoch: 440 - Loss: 46445.593053610195
Epoch: 441 - Loss: 46445.346668523
Epoch: 442 - Loss: 46445.1002861247
Epoch: 443 - Loss: 46444.85390641503
Epoch: 444 - Loss: 46444.60752939378
Epoch: 445 - Loss: 46444.36115506053
Epoch: 446 - Loss: 46444.11478341509
Epoch: 447 - Loss: 46443.86841445717
Epoch: 448 - Loss: 46443.6220481865
Epoch: 449 - Loss: 46443.37568460279
Epoch: 450 - Loss: 46443.12932370575
Epoch: 451 - Loss: 46442.88296549512
Epoch: 452 - Loss: 46442.6366099706
Epoch: 453 - Loss: 46442.39025713195
Epoch: 454 - Loss: 46442.143906978905
Epoch: 455 - Loss: 46441.897559511126
Epoch: 456 - Loss: 46441.65121472835
Epoch: 457 - Loss: 46441.40487263034
Epoch: 458 - Loss: 46441.15853321678
Epoch: 459 - Loss: 46440.9121964874
Epoch: 460 - Loss: 46440.66586244196
Epoch: 461 - Loss: 46440.41953108016
Epoch: 462 - Loss: 46440.17320240172
Epoch: 463 - Loss: 46439.92687640635
Epoch: 464 - Loss: 46439.68055309379
Epoch: 465 - Loss: 46439.43423246379
Epoch: 466 - Loss: 46439.187914516
Epoch: 467 - Loss: 46438.941599250225
Epoch: 468 - Loss: 46438.69528666618
Epoch: 469 - Loss: 46438.448976763546
Epoch: 470 - Loss: 46438.20266954205
Epoch: 471 - Loss: 46437.95636500141
Epoch: 472 - Loss: 46437.71006314144
Epoch: 473 - Loss: 46437.46376396178
Epoch: 474 - Loss: 46437.21746746215
Epoch: 475 - Loss: 46436.97117364233
Epoch: 476 - Loss: 46436.72488250201
Epoch: 477 - Loss: 46436.4785940409
Epoch: 478 - Loss: 46436.23230825878
Epoch: 479 - Loss: 46435.98602515534
Epoch: 480 - Loss: 46435.739744730294
Epoch: 481 - Loss: 46435.49346698336
Epoch: 482 - Loss: 46435.24719191434
Epoch: 483 - Loss: 46435.00091952287
Epoch: 484 - Loss: 46434.75464980876
Epoch: 485 - Loss: 46434.50838277162
Epoch: 486 - Loss: 46434.2621184113
Epoch: 487 - Loss: 46434.01585672745
Epoch: 488 - Loss: 46433.76959771982
Epoch: 489 - Loss: 46433.523341388114
Epoch: 490 - Loss: 46433.27708773209
Epoch: 491 - Loss: 46433.030836751546
Epoch: 492 - Loss: 46432.784588446026
Epoch: 493 - Loss: 46432.538342815446
Epoch: 494 - Loss: 46432.292099859405
Epoch: 495 - Loss: 46432.04585957769
Epoch: 496 - Loss: 46431.79962196996
Epoch: 497 - Loss: 46431.553387036045
Epoch: 498 - Loss: 46431.30715477556
Epoch: 499 - Loss: 46431.06092518835
Epoch: 500 - Loss: 46430.814698274095
Epoch: 501 - Loss: 46430.56847403252
Epoch: 502 - Loss: 46430.32225246327
Epoch: 503 - Loss: 46430.07603356626
Epoch: 504 - Loss: 46429.829817341044
Epoch: 505 - Loss: 46429.58360378744
Epoch: 506 - Loss: 46429.337392905196
Epoch: 507 - Loss: 46429.091184693956
Epoch: 508 - Loss: 46428.84497915345
Epoch: 509 - Loss: 46428.59877628351
Epoch: 510 - Loss: 46428.35257608377
Epoch: 511 - Loss: 46428.10637855404
Epoch: 512 - Loss: 46427.86018369398
Epoch: 513 - Loss: 46427.613991503305
Epoch: 514 - Loss: 46427.36780198183
Epoch: 515 - Loss: 46427.12161512923
Epoch: 516 - Loss: 46426.8754309452
Epoch: 517 - Loss: 46426.62924942955
Epoch: 518 - Loss: 46426.38307058195
Epoch: 519 - Loss: 46426.136894402196
Epoch: 520 - Loss: 46425.89072088992
Epoch: 521 - Loss: 46425.64455004488
Epoch: 522 - Loss: 46425.398381866915
Epoch: 523 - Loss: 46425.152216355615
Epoch: 524 - Loss: 46424.90605351079
Epoch: 525 - Loss: 46424.65989333216
Epoch: 526 - Loss: 46424.41373581943
Epoch: 527 - Loss: 46424.16758097231
Epoch: 528 - Loss: 46423.92142879061
Epoch: 529 - Loss: 46423.675279274015
Epoch: 530 - Loss: 46423.429132422236
Epoch: 531 - Loss: 46423.182988235036
Epoch: 532 - Loss: 46422.93684671216
Epoch: 533 - Loss: 46422.69070785323
Epoch: 534 - Loss: 46422.44457165817
Epoch: 535 - Loss: 46422.1984381266
Epoch: 536 - Loss: 46421.95230725821
Epoch: 537 - Loss: 46421.70617905277
Epoch: 538 - Loss: 46421.460053510054
Epoch: 539 - Loss: 46421.213930629754

{'loss': 48021.83670927769,
 'weight': array([-1.474197918528139, 5.62647066229165, 4.768973033779851,
        4.710261219264584, 1.8731797877089504, 0.2040158591695383,
        -1.237102503675169, 0.6609913245014487, 1.1258718747623089,
        0.4800350498295224, -1.5539439833383755, -0.15493256392669735,
        0.6648490658335175], dtype=object)}

In [20]:
preds = linear_model.predict(X_train)
r2score(preds, y_train)

0.6232921092937094

In [21]:
preds = linear_model.predict(X_test)
r2score(preds, y_test)

0.6420276046412661

#Polynomial Regression

##Simple Approach
**Form**
$(a+b)^2 => a^2 + b^2 + a + b + 1$

In [22]:
def create_polynomial_features(X, degree=2):
    """Creates the polynomial features
    Args:
        X: A array for the data.
        degree: A intege for the degree of
        the generated polynomial function.
    """
    X_mem = []
    for X_sub in X.T:
        X_sub = X_sub.T
        X_new = X_sub
        for d in range(2, degree+1):
            X_new = np.c_[X_new, np.power(X_sub, d)]
        X_mem.extend(X_new.T)
    return np.c_[X_mem].T

In [23]:
X_new = np.array([[1, 2], [3, 4]])
X_new

array([[1, 2],
       [3, 4]])

In [24]:
create_polynomial_features(X_new, degree=2)

array([[ 1,  1,  2,  4],
       [ 3,  9,  4, 16]])

In [25]:
create_polynomial_features(X_new, degree=3)

array([[ 1,  1,  1,  2,  4,  8],
       [ 3,  9, 27,  4, 16, 64]])

In [26]:
X_poly = create_polynomial_features(X, degree=2)
X_poly

array([[23.2, 538.24, 25.4, ..., 0, False, 0],
       [24.0, 576.0, 26.3, ..., 0, False, 0],
       [23.9, 571.2099999999999, 26.5, ..., 0, False, 0],
       ...,
       [12.1, 146.41, 13.0, ..., 1, False, 0],
       [13.2, 174.23999999999998, 14.3, ..., 1, False, 0],
       [13.8, 190.44000000000003, 15.0, ..., 1, False, 0]], dtype=object)

In [27]:
X_poly.shape

(159, 24)

In [28]:
X_data = np.hstack((np.ones((X_poly.shape[0], 1)), X_poly))
X_data

array([[1.0, 23.2, 538.24, ..., 0, False, 0],
       [1.0, 24.0, 576.0, ..., 0, False, 0],
       [1.0, 23.9, 571.2099999999999, ..., 0, False, 0],
       ...,
       [1.0, 12.1, 146.41, ..., 1, False, 0],
       [1.0, 13.2, 174.23999999999998, ..., 1, False, 0],
       [1.0, 13.8, 190.44000000000003, ..., 1, False, 0]], dtype=object)

In [29]:
X_data.shape, y.shape

((159, 25), (159,))

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X_data, y, test_size=0.2, random_state=42)
print('X_train shape: ', X_train.shape)
print('X_test shape: ', X_test.shape)
print('y_train shape: ', y_train.shape)
print('y_train shape: ', y_test.shape)

X_train shape:  (127, 25)
X_test shape:  (32, 25)
y_train shape:  (127,)
y_train shape:  (32,)

In [31]:
poly_model = LinearRegression(X_train, y_train, learning_rate=0.0000001, num_epochs=100000)
poly_model.fit()

Streaming output truncated to the last 5000 lines.
Epoch: 95000 - Loss: 3948.3312979619386
Epoch: 95001 - Loss: 3948.3213620584634
Epoch: 95002 - Loss: 3948.311426286392
Epoch: 95003 - Loss: 3948.301490645725
Epoch: 95004 - Loss: 3948.291555136454
Epoch: 95005 - Loss: 3948.281619758583
Epoch: 95006 - Loss: 3948.271684512112
Epoch: 95007 - Loss: 3948.261749397023
Epoch: 95008 - Loss: 3948.2518144133296
Epoch: 95009 - Loss: 3948.241879561024
Epoch: 95010 - Loss: 3948.231944840109
Epoch: 95011 - Loss: 3948.2220102505653
Epoch: 95012 - Loss: 3948.212075792414
Epoch: 95013 - Loss: 3948.202141465635
Epoch: 95014 - Loss: 3948.1922072702378
Epoch: 95015 - Loss: 3948.182273206212
Epoch: 95016 - Loss: 3948.172339273563
Epoch: 95017 - Loss: 3948.16240547228
Epoch: 95018 - Loss: 3948.1524718023657
Epoch: 95019 - Loss: 3948.1425382638217
Epoch: 95020 - Loss: 3948.132604856632
Epoch: 95021 - Loss: 3948.1226715808098
Epoch: 95022 - Loss: 3948.112738436344
Epoch: 95023 - Loss: 3948.1028054232356
Epoch: 95024 - Loss: 3948.092872541487
Epoch: 95025 - Loss: 3948.082939791074
Epoch: 95026 - Loss: 3948.0730071720354
Epoch: 95027 - Loss: 3948.06307468433
Epoch: 95028 - Loss: 3948.0531423279713
Epoch: 95029 - Loss: 3948.0432101029473
Epoch: 95030 - Loss: 3948.033278009275
Epoch: 95031 - Loss: 3948.0233460469353
Epoch: 95032 - Loss: 3948.0134142159413
Epoch: 95033 - Loss: 3948.003482516272
Epoch: 95034 - Loss: 3947.9935509479396
Epoch: 95035 - Loss: 3947.9836195109233
Epoch: 95036 - Loss: 3947.973688205253
Epoch: 95037 - Loss: 3947.963757030897
Epoch: 95038 - Loss: 3947.953825987874
Epoch: 95039 - Loss: 3947.9438950761582
Epoch: 95040 - Loss: 3947.9339642957725
Epoch: 95041 - Loss: 3947.924033646694
Epoch: 95042 - Loss: 3947.914103128939
Epoch: 95043 - Loss: 3947.90417274249
Epoch: 95044 - Loss: 3947.8942424873476
Epoch: 95045 - Loss: 3947.8843123635156
Epoch: 95046 - Loss: 3947.8743823709965
Epoch: 95047 - Loss: 3947.8644525097643
Epoch: 95048 - Loss: 3947.8545227798427
Epoch: 95049 - Loss: 3947.8445931812084
Epoch: 95050 - Loss: 3947.834663713879
Epoch: 95051 - Loss: 3947.824734377847
Epoch: 95052 - Loss: 3947.814805173102
Epoch: 95053 - Loss: 3947.8048760996426
Epoch: 95054 - Loss: 3947.7949471574793
Epoch: 95055 - Loss: 3947.785018346589
Epoch: 95056 - Loss: 3947.7750896669886
Epoch: 95057 - Loss: 3947.7651611186634
Epoch: 95058 - Loss: 3947.7552327016197
Epoch: 95059 - Loss: 3947.7453044158524
Epoch: 95060 - Loss: 3947.735376261352
Epoch: 95061 - Loss: 3947.725448238131
Epoch: 95062 - Loss: 3947.7155203461784
Epoch: 95063 - Loss: 3947.705592585484
Epoch: 95064 - Loss: 3947.695664956064
Epoch: 95065 - Loss: 3947.685737457896
Epoch: 95066 - Loss: 3947.6758100909933
Epoch: 95067 - Loss: 3947.6658828553504
Epoch: 95068 - Loss: 3947.6559557509636
Epoch: 95069 - Loss: 3947.646028777818
Epoch: 95070 - Loss: 3947.636101935935
Epoch: 95071 - Loss: 3947.626175225297
Epoch: 95072 - Loss: 3947.6162486459075
Epoch: 95073 - Loss: 3947.606322197763
Epoch: 95074 - Loss: 3947.5963958808607
Epoch: 95075 - Loss: 3947.5864696951944
Epoch: 95076 - Loss: 3947.5765436407646
Epoch: 95077 - Loss: 3947.5666177175763
Epoch: 95078 - Loss: 3947.5566919256107
Epoch: 95079 - Loss: 3947.5467662648857
Epoch: 95080 - Loss: 3947.536840735386
Epoch: 95081 - Loss: 3947.5269153371173
Epoch: 95082 - Loss: 3947.5169900700607
Epoch: 95083 - Loss: 3947.5070649342338
Epoch: 95084 - Loss: 3947.4971399296237
Epoch: 95085 - Loss: 3947.4872150562305
Epoch: 95086 - Loss: 3947.477290314055
Epoch: 95087 - Loss: 3947.467365703088
Epoch: 95088 - Loss: 3947.4574412233355
Epoch: 95089 - Loss: 3947.4475168747895
Epoch: 95090 - Loss: 3947.437592657452
Epoch: 95091 - Loss: 3947.4276685713157
Epoch: 95092 - Loss: 3947.4177446163803
Epoch: 95093 - Loss: 3947.407820792644
Epoch: 95094 - Loss: 3947.3978971001106
Epoch: 95095 - Loss: 3947.3879735387645
Epoch: 95096 - Loss: 3947.378050108617
Epoch: 95097 - Loss: 3947.368126809653
Epoch: 95098 - Loss: 3947.3582036418816
Epoch: 95099 - Loss: 3947.3482806052925
Epoch: 95100 - Loss: 3947.3383576998954
Epoch: 95101 - Loss: 3947.328434925666
Epoch: 95102 - Loss: 3947.3185122826276
Epoch: 95103 - Loss: 3947.3085897707647
Epoch: 95104 - Loss: 3947.298667390067
Epoch: 95105 - Loss: 3947.2887451405486
Epoch: 95106 - Loss: 3947.2788230222
Epoch: 95107 - Loss: 3947.2689010350155
Epoch: 95108 - Loss: 3947.258979179003
Epoch: 95109 - Loss: 3947.2490574541453
Epoch: 95110 - Loss: 3947.2391358604636
Epoch: 95111 - Loss: 3947.2292143979257
Epoch: 95112 - Loss: 3947.2192930665497
Epoch: 95113 - Loss: 3947.2093718663295
Epoch: 95114 - Loss: 3947.1994507972577
Epoch: 95115 - Loss: 3947.189529859338
Epoch: 95116 - Loss: 3947.179609052566
Epoch: 95117 - Loss: 3947.169688376936
Epoch: 95118 - Loss: 3947.1597678324483
Epoch: 95119 - Loss: 3947.1498474191053
Epoch: 95120 - Loss: 3947.1399271368964
Epoch: 95121 - Loss: 3947.130006985841
Epoch: 95122 - Loss: 3947.1200869659037
Epoch: 95123 - Loss: 3947.1101670771036
Epoch: 95124 - Loss: 3947.1002473194303
Epoch: 95125 - Loss: 3947.0903276928802
Epoch: 95126 - Loss: 3947.0804081974634
Epoch: 95127 - Loss: 3947.070488833162
Epoch: 95128 - Loss: 3947.0605695999943
Epoch: 95129 - Loss: 3947.0506504979285
Epoch: 95130 - Loss: 3947.0407315269913
Epoch: 95131 - Loss: 3947.030812687159
Epoch: 95132 - Loss: 3947.0208939784516
Epoch: 95133 - Loss: 3947.010975400844
Epoch: 95134 - Loss: 3947.0010569543356
Epoch: 95135 - Loss: 3946.9911386389463
Epoch: 95136 - Loss: 3946.9812204546542
Epoch: 95137 - Loss: 3946.9713024014613
Epoch: 95138 - Loss: 3946.9613844793653
Epoch: 95139 - Loss: 3946.9514666883706
Epoch: 95140 - Loss: 3946.9415490284696
Epoch: 95141 - Loss: 3946.9316314996527
Epoch: 95142 - Loss: 3946.9217141019303
Epoch: 95143 - Loss: 3946.9117968353007
Epoch: 95144 - Loss: 3946.9018796997493
Epoch: 95145 - Loss: 3946.8919626952807
Epoch: 95146 - Loss: 3946.8820458218947
Epoch: 95147 - Loss: 3946.8721290795875
Epoch: 95148 - Loss: 3946.8622124683543
Epoch: 95149 - Loss: 3946.852295988194
Epoch: 95150 - Loss: 3946.842379639104
Epoch: 95151 - Loss: 3946.832463421086
Epoch: 95152 - Loss: 3946.8225473341313
Epoch: 95153 - Loss: 3946.8126313782395
Epoch: 95154 - Loss: 3946.8027155534096
Epoch: 95155 - Loss: 3946.792799859645
Epoch: 95156 - Loss: 3946.7828842969398
Epoch: 95157 - Loss: 3946.772968865291
Epoch: 95158 - Loss: 3946.763053564692
Epoch: 95159 - Loss: 3946.7531383951464
Epoch: 95160 - Loss: 3946.7432233566497
Epoch: 95161 - Loss: 3946.733308449189
Epoch: 95162 - Loss: 3946.7233936727835
Epoch: 95163 - Loss: 3946.713479027419
Epoch: 95164 - Loss: 3946.703564513091
Epoch: 95165 - Loss: 3946.6936501297987
Epoch: 95166 - Loss: 3946.683735877548
Epoch: 95167 - Loss: 3946.6738217563334
Epoch: 95168 - Loss: 3946.6639077661475
Epoch: 95169 - Loss: 3946.653993906987
Epoch: 95170 - Loss: 3946.6440801788576
Epoch: 95171 - Loss: 3946.634166581749
Epoch: 95172 - Loss: 3946.6242531156636
Epoch: 95173 - Loss: 3946.61433978059
Epoch: 95174 - Loss: 3946.6044265765454
Epoch: 95175 - Loss: 3946.594513503512
Epoch: 95176 - Loss: 3946.584600561488
Epoch: 95177 - Loss: 3946.574687750479
Epoch: 95178 - Loss: 3946.5647750704848
Epoch: 95179 - Loss: 3946.554862521486
Epoch: 95180 - Loss: 3946.5449501035005
Epoch: 95181 - Loss: 3946.5350378165094
Epoch: 95182 - Loss: 3946.5251256605184
Epoch: 95183 - Loss: 3946.515213635525
Epoch: 95184 - Loss: 3946.5053017415376
Epoch: 95185 - Loss: 3946.4953899785232
Epoch: 95186 - Loss: 3946.4854783465175
Epoch: 95187 - Loss: 3946.4755668454936
Epoch: 95188 - Loss: 3946.4656554754547
Epoch: 95189 - Loss: 3946.4557442363953
Epoch: 95190 - Loss: 3946.4458331283304
Epoch: 95191 - Loss: 3946.435922151237
Epoch: 95192 - Loss: 3946.4260113051137
Epoch: 95193 - Loss: 3946.416100589975
Epoch: 95194 - Loss: 3946.4061900058073
Epoch: 95195 - Loss: 3946.396279552617
Epoch: 95196 - Loss: 3946.3863692303744
Epoch: 95197 - Loss: 3946.3764590391206
Epoch: 95198 - Loss: 3946.366548978815
Epoch: 95199 - Loss: 3946.356639049485
Epoch: 95200 - Loss: 3946.3467292511036
Epoch: 95201 - Loss: 3946.336819583681
Epoch: 95202 - Loss: 3946.3269100472185
Epoch: 95203 - Loss: 3946.3170006417035
Epoch: 95204 - Loss: 3946.3070913671427
Epoch: 95205 - Loss: 3946.2971822235286
Epoch: 95206 - Loss: 3946.2872732108544
Epoch: 95207 - Loss: 3946.27736432913
Epoch: 95208 - Loss: 3946.2674555783474
Epoch: 95209 - Loss: 3946.257546958504
Epoch: 95210 - Loss: 3946.2476384695997
Epoch: 95211 - Loss: 3946.237730111621
Epoch: 95212 - Loss: 3946.2278218845804
Epoch: 95213 - Loss: 3946.2179137884723
Epoch: 95214 - Loss: 3946.2080058232914
Epoch: 95215 - Loss: 3946.1980979890345
Epoch: 95216 - Loss: 3946.188190285709
Epoch: 95217 - Loss: 3946.178282713294
Epoch: 95218 - Loss: 3946.1683752717945
Epoch: 95219 - Loss: 3946.158467961231
Epoch: 95220 - Loss: 3946.1485607815616
Epoch: 95221 - Loss: 3946.1386537328167
Epoch: 95222 - Loss: 3946.1287468149776
Epoch: 95223 - Loss: 3946.1188400280475
Epoch: 95224 - Loss: 3946.1089333720197
Epoch: 95225 - Loss: 3946.0990268468972
Epoch: 95226 - Loss: 3946.089120452675
Epoch: 95227 - Loss: 3946.0792141893603
Epoch: 95228 - Loss: 3946.069308056938
Epoch: 95229 - Loss: 3946.0594020554004
Epoch: 95230 - Loss: 3946.0494961847685
Epoch: 95231 - Loss: 3946.039590445022
Epoch: 95232 - Loss: 3946.0296848361595
Epoch: 95233 - Loss: 3946.0197793581883
Epoch: 95234 - Loss: 3946.009874011096
Epoch: 95235 - Loss: 3945.9999687948875
Epoch: 95236 - Loss: 3945.9900637095516
Epoch: 95237 - Loss: 3945.9801587550987
Epoch: 95238 - Loss: 3945.9702539315185
Epoch: 95239 - Loss: 3945.9603492388073
Epoch: 95240 - Loss: 3945.950444676971
Epoch: 95241 - Loss: 3945.9405402459997
Epoch: 95242 - Loss: 3945.930635945894
Epoch: 95243 - Loss: 3945.9207317766536
Epoch: 95244 - Loss: 3945.91082773827
Epoch: 95245 - Loss: 3945.9009238307517
Epoch: 95246 - Loss: 3945.8910200540868
Epoch: 95247 - Loss: 3945.881116408281
Epoch: 95248 - Loss: 3945.871212893317
Epoch: 95249 - Loss: 3945.8613095092087
Epoch: 95250 - Loss: 3945.851406255943
Epoch: 95251 - Loss: 3945.841503133529
Epoch: 95252 - Loss: 3945.8316001419553
Epoch: 95253 - Loss: 3945.8216972812193
Epoch: 95254 - Loss: 3945.8117945513345
Epoch: 95255 - Loss: 3945.801891952271
Epoch: 95256 - Loss: 3945.7919894840525
Epoch: 95257 - Loss: 3945.7820871466633
Epoch: 95258 - Loss: 3945.772184940093
Epoch: 95259 - Loss: 3945.7622828643616
Epoch: 95260 - Loss: 3945.752380919452
Epoch: 95261 - Loss: 3945.7424791053713
Epoch: 95262 - Loss: 3945.732577422093
Epoch: 95263 - Loss: 3945.7226758696534
Epoch: 95264 - Loss: 3945.7127744480285
Epoch: 95265 - Loss: 3945.702873157208
Epoch: 95266 - Loss: 3945.6929719972013
Epoch: 95267 - Loss: 3945.6830709680075
Epoch: 95268 - Loss: 3945.673170069618
Epoch: 95269 - Loss: 3945.663269302032
Epoch: 95270 - Loss: 3945.65336866526
Epoch: 95271 - Loss: 3945.643468159269
Epoch: 95272 - Loss: 3945.633567784091
Epoch: 95273 - Loss: 3945.6236675397136
Epoch: 95274 - Loss: 3945.613767426121
Epoch: 95275 - Loss: 3945.6038674433225
Epoch: 95276 - Loss: 3945.5939675913114
Epoch: 95277 - Loss: 3945.5840678700893
Epoch: 95278 - Loss: 3945.57416827965
Epoch: 95279 - Loss: 3945.5642688199905
Epoch: 95280 - Loss: 3945.554369491119
Epoch: 95281 - Loss: 3945.5444702930313
Epoch: 95282 - Loss: 3945.534571225708
Epoch: 95283 - Loss: 3945.524672289161
Epoch: 95284 - Loss: 3945.5147734833895
Epoch: 95285 - Loss: 3945.504874808387
Epoch: 95286 - Loss: 3945.494976264143
Epoch: 95287 - Loss: 3945.4850778506757
Epoch: 95288 - Loss: 3945.4751795679636
Epoch: 95289 - Loss: 3945.465281416017
Epoch: 95290 - Loss: 3945.4553833948285
Epoch: 95291 - Loss: 3945.4454855043855
Epoch: 95292 - Loss: 3945.4355877447165
Epoch: 95293 - Loss: 3945.4256901157746
Epoch: 95294 - Loss: 3945.415792617604
Epoch: 95295 - Loss: 3945.405895250161
Epoch: 95296 - Loss: 3945.395998013476
Epoch: 95297 - Loss: 3945.386100907531
Epoch: 95298 - Loss: 3945.3762039323196
Epoch: 95299 - Loss: 3945.366307087859
Epoch: 95300 - Loss: 3945.3564103741223
Epoch: 95301 - Loss: 3945.34651379113
Epoch: 95302 - Loss: 3945.3366173388613
Epoch: 95303 - Loss: 3945.3267210173244
Epoch: 95304 - Loss: 3945.316824826514
Epoch: 95305 - Loss: 3945.3069287664307
Epoch: 95306 - Loss: 3945.29703283706
Epoch: 95307 - Loss: 3945.287137038425
Epoch: 95308 - Loss: 3945.277241370502
Epoch: 95309 - Loss: 3945.2673458332943
Epoch: 95310 - Loss: 3945.257450426796
Epoch: 95311 - Loss: 3945.2475551510124
Epoch: 95312 - Loss: 3945.237660005941
Epoch: 95313 - Loss: 3945.2277649915713
Epoch: 95314 - Loss: 3945.217870107914
Epoch: 95315 - Loss: 3945.2079753549497
Epoch: 95316 - Loss: 3945.1980807326895
Epoch: 95317 - Loss: 3945.188186241128
Epoch: 95318 - Loss: 3945.178291880263
Epoch: 95319 - Loss: 3945.1683976500863
Epoch: 95320 - Loss: 3945.1585035506087
Epoch: 95321 - Loss: 3945.1486095818195
Epoch: 95322 - Loss: 3945.1387157437152
Epoch: 95323 - Loss: 3945.128822036297
Epoch: 95324 - Loss: 3945.118928459553
Epoch: 95325 - Loss: 3945.109035013498
Epoch: 95326 - Loss: 3945.099141698117
Epoch: 95327 - Loss: 3945.089248513408
Epoch: 95328 - Loss: 3945.0793554593793
Epoch: 95329 - Loss: 3945.0694625360193
Epoch: 95330 - Loss: 3945.0595697433355
Epoch: 95331 - Loss: 3945.04967708131
Epoch: 95332 - Loss: 3945.0397845499538
Epoch: 95333 - Loss: 3945.0298921492536
Epoch: 95334 - Loss: 3945.0199998792214
Epoch: 95335 - Loss: 3945.010107739842
Epoch: 95336 - Loss: 3945.0002157311146
Epoch: 95337 - Loss: 3944.990323853046
Epoch: 95338 - Loss: 3944.9804321056286
Epoch: 95339 - Loss: 3944.9705404888587
Epoch: 95340 - Loss: 3944.960649002734
Epoch: 95341 - Loss: 3944.950757647261
Epoch: 95342 - Loss: 3944.94086642242
Epoch: 95343 - Loss: 3944.9309753282337
Epoch: 95344 - Loss: 3944.9210843646606
Epoch: 95345 - Loss: 3944.9111935317464
Epoch: 95346 - Loss: 3944.9013028294594
Epoch: 95347 - Loss: 3944.891412257797
Epoch: 95348 - Loss: 3944.881521816773
Epoch: 95349 - Loss: 3944.8716315063675
Epoch: 95350 - Loss: 3944.8617413265943
Epoch: 95351 - Loss: 3944.851851277437
Epoch: 95352 - Loss: 3944.8419613589017
Epoch: 95353 - Loss: 3944.8320715709815
Epoch: 95354 - Loss: 3944.822181913682
Epoch: 95355 - Loss: 3944.8122923870005
Epoch: 95356 - Loss: 3944.8024029909166
Epoch: 95357 - Loss: 3944.7925137254547
Epoch: 95358 - Loss: 3944.7826245905844
Epoch: 95359 - Loss: 3944.7727355863312
Epoch: 95360 - Loss: 3944.762846712672
Epoch: 95361 - Loss: 3944.752957969619
Epoch: 95362 - Loss: 3944.743069357167
Epoch: 95363 - Loss: 3944.733180875303
Epoch: 95364 - Loss: 3944.723292524032
Epoch: 95365 - Loss: 3944.7134043033593
Epoch: 95366 - Loss: 3944.7035162132674
Epoch: 95367 - Loss: 3944.6936282537686
Epoch: 95368 - Loss: 3944.6837404248454
Epoch: 95369 - Loss: 3944.673852726508
Epoch: 95370 - Loss: 3944.663965158752
Epoch: 95371 - Loss: 3944.6540777215737
Epoch: 95372 - Loss: 3944.644190414979
Epoch: 95373 - Loss: 3944.634303238948
Epoch: 95374 - Loss: 3944.62441619349
Epoch: 95375 - Loss: 3944.614529278601
Epoch: 95376 - Loss: 3944.6046424942806
Epoch: 95377 - Loss: 3944.5947558405187
Epoch: 95378 - Loss: 3944.584869317322
Epoch: 95379 - Loss: 3944.5749829246947
Epoch: 95380 - Loss: 3944.565096662612
Epoch: 95381 - Loss: 3944.5552105310917
Epoch: 95382 - Loss: 3944.545324530124
Epoch: 95383 - Loss: 3944.5354386597055
Epoch: 95384 - Loss: 3944.525552919833
Epoch: 95385 - Loss: 3944.515667310511
Epoch: 95386 - Loss: 3944.505781831733
Epoch: 95387 - Loss: 3944.495896483491
Epoch: 95388 - Loss: 3944.4860112657952
Epoch: 95389 - Loss: 3944.4761261786416
Epoch: 95390 - Loss: 3944.466241222016
Epoch: 95391 - Loss: 3944.456356395932
Epoch: 95392 - Loss: 3944.4464717003684
Epoch: 95393 - Loss: 3944.436587135336
Epoch: 95394 - Loss: 3944.4267027008405
Epoch: 95395 - Loss: 3944.4168183968554
Epoch: 95396 - Loss: 3944.4069342233975
Epoch: 95397 - Loss: 3944.397050180457
Epoch: 95398 - Loss: 3944.3871662680363
Epoch: 95399 - Loss: 3944.377282486133
Epoch: 95400 - Loss: 3944.3673988347414
Epoch: 95401 - Loss: 3944.3575153138677
Epoch: 95402 - Loss: 3944.3476319234896
Epoch: 95403 - Loss: 3944.3377486636223
Epoch: 95404 - Loss: 3944.3278655342674
Epoch: 95405 - Loss: 3944.3179825354073
Epoch: 95406 - Loss: 3944.3080996670456
Epoch: 95407 - Loss: 3944.298216929187
Epoch: 95408 - Loss: 3944.2883343218223
Epoch: 95409 - Loss: 3944.2784518449516
Epoch: 95410 - Loss: 3944.26856949857
Epoch: 95411 - Loss: 3944.2586872826764
Epoch: 95412 - Loss: 3944.248805197275
Epoch: 95413 - Loss: 3944.2389232423507
Epoch: 95414 - Loss: 3944.229041417911
Epoch: 95415 - Loss: 3944.219159723947
Epoch: 95416 - Loss: 3944.2092781604674
Epoch: 95417 - Loss: 3944.1993967274598
Epoch: 95418 - Loss: 3944.1895154249264
Epoch: 95419 - Loss: 3944.1796342528637
Epoch: 95420 - Loss: 3944.16975321127
Epoch: 95421 - Loss: 3944.1598723001384
Epoch: 95422 - Loss: 3944.1499915194827
Epoch: 95423 - Loss: 3944.140110869277
Epoch: 95424 - Loss: 3944.1302303495418
Epoch: 95425 - Loss: 3944.1203499602602
Epoch: 95426 - Loss: 3944.1104697014343
Epoch: 95427 - Loss: 3944.1005895730545
Epoch: 95428 - Loss: 3944.090709575131
Epoch: 95429 - Loss: 3944.0808297076587
Epoch: 95430 - Loss: 3944.0709499706322
Epoch: 95431 - Loss: 3944.061070364048
Epoch: 95432 - Loss: 3944.051190887905
Epoch: 95433 - Loss: 3944.0413115422048
Epoch: 95434 - Loss: 3944.031432326943
Epoch: 95435 - Loss: 3944.0215532421134
Epoch: 95436 - Loss: 3944.011674287714
Epoch: 95437 - Loss: 3944.001795463749
Epoch: 95438 - Loss: 3943.991916770213
Epoch: 95439 - Loss: 3943.982038207104
Epoch: 95440 - Loss: 3943.972159774419
Epoch: 95441 - Loss: 3943.962281472153
Epoch: 95442 - Loss: 3943.952403300314
Epoch: 95443 - Loss: 3943.9425252588912
Epoch: 95444 - Loss: 3943.932647347875
Epoch: 95445 - Loss: 3943.9227695672867
Epoch: 95446 - Loss: 3943.912891917098
Epoch: 95447 - Loss: 3943.9030143973237
Epoch: 95448 - Loss: 3943.893137007952
Epoch: 95449 - Loss: 3943.8832597489827
Epoch: 95450 - Loss: 3943.8733826204184
Epoch: 95451 - Loss: 3943.8635056222574
Epoch: 95452 - Loss: 3943.8536287544916
Epoch: 95453 - Loss: 3943.8437520171224
Epoch: 95454 - Loss: 3943.8338754101424
Epoch: 95455 - Loss: 3943.8239989335593
Epoch: 95456 - Loss: 3943.8141225873583
Epoch: 95457 - Loss: 3943.8042463715487
Epoch: 95458 - Loss: 3943.7943702861226
Epoch: 95459 - Loss: 3943.784494331077
Epoch: 95460 - Loss: 3943.7746185064143
Epoch: 95461 - Loss: 3943.7647428121318
Epoch: 95462 - Loss: 3943.7548672482258
Epoch: 95463 - Loss: 3943.74499181468
Epoch: 95464 - Loss: 3943.735116511515
Epoch: 95465 - Loss: 3943.7252413387164
Epoch: 95466 - Loss: 3943.7153662962837
Epoch: 95467 - Loss: 3943.705491384223
Epoch: 95468 - Loss: 3943.6956166025125
Epoch: 95469 - Loss: 3943.6857419511707
Epoch: 95470 - Loss: 3943.6758674301873
Epoch: 95471 - Loss: 3943.6659930395554
Epoch: 95472 - Loss: 3943.656118779271
Epoch: 95473 - Loss: 3943.6462446493506
Epoch: 95474 - Loss: 3943.6363706497646
Epoch: 95475 - Loss: 3943.626496780532
Epoch: 95476 - Loss: 3943.616623041646
Epoch: 95477 - Loss: 3943.6067494331055
Epoch: 95478 - Loss: 3943.596875954901
Epoch: 95479 - Loss: 3943.5870026070297
Epoch: 95480 - Loss: 3943.5771293895036
Epoch: 95481 - Loss: 3943.567256302302
Epoch: 95482 - Loss: 3943.5573833454355
Epoch: 95483 - Loss: 3943.5475105188943
Epoch: 95484 - Loss: 3943.537637822689
Epoch: 95485 - Loss: 3943.5277652568006
Epoch: 95486 - Loss: 3943.5178928212354
Epoch: 95487 - Loss: 3943.5080205159898
Epoch: 95488 - Loss: 3943.498148341062
Epoch: 95489 - Loss: 3943.488276296448
Epoch: 95490 - Loss: 3943.478404382153
Epoch: 95491 - Loss: 3943.468532598171
Epoch: 95492 - Loss: 3943.4586609444896
Epoch: 95493 - Loss: 3943.4487894211215
Epoch: 95494 - Loss: 3943.438918028057
Epoch: 95495 - Loss: 3943.429046765286
Epoch: 95496 - Loss: 3943.4191756328237
Epoch: 95497 - Loss: 3943.4093046306525
Epoch: 95498 - Loss: 3943.399433758787
Epoch: 95499 - Loss: 3943.389563017215
Epoch: 95500 - Loss: 3943.379692405922
Epoch: 95501 - Loss: 3943.3698219249322
Epoch: 95502 - Loss: 3943.3599515742217
Epoch: 95503 - Loss: 3943.3500813537958

{'loss': 5440.416873315407,
 'weight': array([-1.186024227732807, -0.10625703399013225, -0.04161137893238147,
        -4.653702364805961, 1.1863107327078892, -3.5619985367762474,
        -0.6207557436006802, -0.6689185458062696, 1.947530084586497,
        -0.5686950910991957, 3.813984144585377, 0.8752262580394873,
        -2.7287508200363035, 0.4378940179478794, 1.1457152589350312,
        1.4249184692563206, 0.32422072875766383, -0.3134837200595102,
        -0.6541526454339001, -0.4881218419800449, -0.9384350478054749,
        0.486971417882043, -2.412084122337565, 0.740066233431221,
        -0.538389677544446], dtype=object)}

In [32]:
preds = poly_model.predict(X_train)
r2score(preds, y_train)

0.9682721437781945

In [33]:
preds = poly_model.predict(X_test)
r2score(preds, y_test)

0.9721394733658284

## **Sklearn**

In [36]:
X.shape

(159, 12)

In [37]:
y.shape

(159,)

In [38]:
from sklearn.preprocessing import PolynomialFeatures

In [39]:
poly_features = PolynomialFeatures(degree=2)

In [41]:
X_data = poly_features.fit_transform(X)
X_data

array([[ 1. , 23.2, 25.4, ...,  0. ,  0. ,  0. ],
       [ 1. , 24. , 26.3, ...,  0. ,  0. ,  0. ],
       [ 1. , 23.9, 26.5, ...,  0. ,  0. ,  0. ],
       ...,
       [ 1. , 12.1, 13. , ...,  1. ,  0. ,  0. ],
       [ 1. , 13.2, 14.3, ...,  1. ,  0. ,  0. ],
       [ 1. , 13.8, 15. , ...,  1. ,  0. ,  0. ]])

In [42]:
X_data.shape

(159, 91)

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X_data, y, test_size=0.2, random_state=42)
print('X_train shape: ', X_train.shape)
print('X_test shape: ', X_test.shape)
print('y_train shape: ', y_train.shape)
print('y_train shape: ', y_test.shape)

X_train shape:  (127, 91)
X_test shape:  (32, 91)
y_train shape:  (127,)
y_train shape:  (32,)

In [45]:
poly_model = LinearRegression(X_train, y_train, learning_rate=0.0000001, num_epochs=100000)
poly_model.fit()

Streaming output truncated to the last 5000 lines.
Epoch: 95000 - Loss: 2552.734246503757
Epoch: 95001 - Loss: 2552.7272358010855
Epoch: 95002 - Loss: 2552.7202252500197
Epoch: 95003 - Loss: 2552.7132148505802
Epoch: 95004 - Loss: 2552.706204602776
Epoch: 95005 - Loss: 2552.699194506571
Epoch: 95006 - Loss: 2552.6921845619763
Epoch: 95007 - Loss: 2552.685174768977
Epoch: 95008 - Loss: 2552.6781651275764
Epoch: 95009 - Loss: 2552.671155637786
Epoch: 95010 - Loss: 2552.6641462995767
Epoch: 95011 - Loss: 2552.6571371129644
Epoch: 95012 - Loss: 2552.650128077929
Epoch: 95013 - Loss: 2552.6431191944735
Epoch: 95014 - Loss: 2552.6361104625926
Epoch: 95015 - Loss: 2552.629101882284
Epoch: 95016 - Loss: 2552.6220934535413
Epoch: 95017 - Loss: 2552.615085176357
Epoch: 95018 - Loss: 2552.608077050732
Epoch: 95019 - Loss: 2552.6010690766684
Epoch: 95020 - Loss: 2552.594061254154
Epoch: 95021 - Loss: 2552.5870535831828
Epoch: 95022 - Loss: 2552.580046063754
Epoch: 95023 - Loss: 2552.5730386958653
Epoch: 95024 - Loss: 2552.5660314795086
Epoch: 95025 - Loss: 2552.5590244146842
Epoch: 95026 - Loss: 2552.552017501384
Epoch: 95027 - Loss: 2552.545010739602
Epoch: 95028 - Loss: 2552.5380041293356
Epoch: 95029 - Loss: 2552.5309976705958
Epoch: 95030 - Loss: 2552.523991363354
Epoch: 95031 - Loss: 2552.516985207616
Epoch: 95032 - Loss: 2552.509979203382
Epoch: 95033 - Loss: 2552.502973350645
Epoch: 95034 - Loss: 2552.4959676494045
Epoch: 95035 - Loss: 2552.488962099649
Epoch: 95036 - Loss: 2552.4819567013765
Epoch: 95037 - Loss: 2552.4749514545824
Epoch: 95038 - Loss: 2552.4679463592665
Epoch: 95039 - Loss: 2552.4609414154247
Epoch: 95040 - Loss: 2552.453936623052
Epoch: 95041 - Loss: 2552.446931982143
Epoch: 95042 - Loss: 2552.439927492678
Epoch: 95043 - Loss: 2552.432923154681
Epoch: 95044 - Loss: 2552.4259189681384
Epoch: 95045 - Loss: 2552.41891493305
Epoch: 95046 - Loss: 2552.41191104939
Epoch: 95047 - Loss: 2552.404907317179
Epoch: 95048 - Loss: 2552.397903736393
Epoch: 95049 - Loss: 2552.3909003070394
Epoch: 95050 - Loss: 2552.383897029113
Epoch: 95051 - Loss: 2552.3768939026118
Epoch: 95052 - Loss: 2552.369890927527
Epoch: 95053 - Loss: 2552.362888103861
Epoch: 95054 - Loss: 2552.355885431595
Epoch: 95055 - Loss: 2552.348882910751
Epoch: 95056 - Loss: 2552.341880541297
Epoch: 95057 - Loss: 2552.334878323237
Epoch: 95058 - Loss: 2552.3278762565756
Epoch: 95059 - Loss: 2552.320874341305
Epoch: 95060 - Loss: 2552.3138725774197
Epoch: 95061 - Loss: 2552.3068709649197
Epoch: 95062 - Loss: 2552.299869503788
Epoch: 95063 - Loss: 2552.2928681940375
Epoch: 95064 - Loss: 2552.2858670356513
Epoch: 95065 - Loss: 2552.27886602863
Epoch: 95066 - Loss: 2552.271865172969
Epoch: 95067 - Loss: 2552.2648644686633
Epoch: 95068 - Loss: 2552.257863915711
Epoch: 95069 - Loss: 2552.25086351411
Epoch: 95070 - Loss: 2552.2438632638473
Epoch: 95071 - Loss: 2552.236863164931
Epoch: 95072 - Loss: 2552.2298632173506
Epoch: 95073 - Loss: 2552.2228634210946
Epoch: 95074 - Loss: 2552.2158637761668
Epoch: 95075 - Loss: 2552.2088642825674
Epoch: 95076 - Loss: 2552.20186494028
Epoch: 95077 - Loss: 2552.194865749318
Epoch: 95078 - Loss: 2552.187866709661
Epoch: 95079 - Loss: 2552.1808678213197
Epoch: 95080 - Loss: 2552.1738690842703
Epoch: 95081 - Loss: 2552.166870498521
Epoch: 95082 - Loss: 2552.1598720640727
Epoch: 95083 - Loss: 2552.1528737809112
Epoch: 95084 - Loss: 2552.145875649033
Epoch: 95085 - Loss: 2552.1388776684357
Epoch: 95086 - Loss: 2552.131879839118
Epoch: 95087 - Loss: 2552.124882161085
Epoch: 95088 - Loss: 2552.1178846343114
Epoch: 95089 - Loss: 2552.1108872588093
Epoch: 95090 - Loss: 2552.103890034564
Epoch: 95091 - Loss: 2552.0968929615788
Epoch: 95092 - Loss: 2552.0898960398463
Epoch: 95093 - Loss: 2552.082899269362
Epoch: 95094 - Loss: 2552.0759026501237
Epoch: 95095 - Loss: 2552.0689061821226
Epoch: 95096 - Loss: 2552.061909865368
Epoch: 95097 - Loss: 2552.0549136998375
Epoch: 95098 - Loss: 2552.047917685536
Epoch: 95099 - Loss: 2552.0409218224722
Epoch: 95100 - Loss: 2552.0339261106174
Epoch: 95101 - Loss: 2552.026930549969
Epoch: 95102 - Loss: 2552.019935140549
Epoch: 95103 - Loss: 2552.0129398823406
Epoch: 95104 - Loss: 2552.0059447753124
Epoch: 95105 - Loss: 2551.9989498195087
Epoch: 95106 - Loss: 2551.9919550148957
Epoch: 95107 - Loss: 2551.9849603614643
Epoch: 95108 - Loss: 2551.9779658592283
Epoch: 95109 - Loss: 2551.9709715081717
Epoch: 95110 - Loss: 2551.963977308298
Epoch: 95111 - Loss: 2551.9569832595994
Epoch: 95112 - Loss: 2551.9499893620664
Epoch: 95113 - Loss: 2551.9429956157123
Epoch: 95114 - Loss: 2551.936002020508
Epoch: 95115 - Loss: 2551.929008576467
Epoch: 95116 - Loss: 2551.922015283579
Epoch: 95117 - Loss: 2551.915022141847
Epoch: 95118 - Loss: 2551.908029151248
Epoch: 95119 - Loss: 2551.9010363118086
Epoch: 95120 - Loss: 2551.8940436235002
Epoch: 95121 - Loss: 2551.887051086318
Epoch: 95122 - Loss: 2551.880058700273
Epoch: 95123 - Loss: 2551.873066465354
Epoch: 95124 - Loss: 2551.8660743815626
Epoch: 95125 - Loss: 2551.859082448879
Epoch: 95126 - Loss: 2551.852090667313
Epoch: 95127 - Loss: 2551.845099036856
Epoch: 95128 - Loss: 2551.838107557504
Epoch: 95129 - Loss: 2551.831116229248
Epoch: 95130 - Loss: 2551.8241250520964
Epoch: 95131 - Loss: 2551.8171340260387
Epoch: 95132 - Loss: 2551.810143151061
Epoch: 95133 - Loss: 2551.803152427175
Epoch: 95134 - Loss: 2551.79616185437
Epoch: 95135 - Loss: 2551.789171432635
Epoch: 95136 - Loss: 2551.782181161985
Epoch: 95137 - Loss: 2551.77519104239
Epoch: 95138 - Loss: 2551.7682010738627
Epoch: 95139 - Loss: 2551.7612112563925
Epoch: 95140 - Loss: 2551.7542215899866
Epoch: 95141 - Loss: 2551.747232074621
Epoch: 95142 - Loss: 2551.7402427103075
Epoch: 95143 - Loss: 2551.7332534970496
Epoch: 95144 - Loss: 2551.7262644348166
Epoch: 95145 - Loss: 2551.7192755236283
Epoch: 95146 - Loss: 2551.712286763471
Epoch: 95147 - Loss: 2551.7052981543266
Epoch: 95148 - Loss: 2551.698309696216
Epoch: 95149 - Loss: 2551.6913213891266
Epoch: 95150 - Loss: 2551.6843332330463
Epoch: 95151 - Loss: 2551.677345227977
Epoch: 95152 - Loss: 2551.6703573739105
Epoch: 95153 - Loss: 2551.663369670856
Epoch: 95154 - Loss: 2551.6563821187938
Epoch: 95155 - Loss: 2551.6493947177305
Epoch: 95156 - Loss: 2551.6424074676506
Epoch: 95157 - Loss: 2551.635420368557
Epoch: 95158 - Loss: 2551.628433420455
Epoch: 95159 - Loss: 2551.6214466233228
Epoch: 95160 - Loss: 2551.614459977159
Epoch: 95161 - Loss: 2551.607473481971
Epoch: 95162 - Loss: 2551.6004871377563
Epoch: 95163 - Loss: 2551.593500944489
Epoch: 95164 - Loss: 2551.5865149021884
Epoch: 95165 - Loss: 2551.579529010837
Epoch: 95166 - Loss: 2551.5725432704385
Epoch: 95167 - Loss: 2551.5655576809772
Epoch: 95168 - Loss: 2551.5585722424553
Epoch: 95169 - Loss: 2551.551586954878
Epoch: 95170 - Loss: 2551.544601818238
Epoch: 95171 - Loss: 2551.537616832511
Epoch: 95172 - Loss: 2551.530631997717
Epoch: 95173 - Loss: 2551.523647313849
Epoch: 95174 - Loss: 2551.516662780893
Epoch: 95175 - Loss: 2551.5096783988447
Epoch: 95176 - Loss: 2551.5026941676983
Epoch: 95177 - Loss: 2551.495710087471
Epoch: 95178 - Loss: 2551.48872615814
Epoch: 95179 - Loss: 2551.4817423796967
Epoch: 95180 - Loss: 2551.4747587521483
Epoch: 95181 - Loss: 2551.467775275485
Epoch: 95182 - Loss: 2551.4607919497066
Epoch: 95183 - Loss: 2551.4538087748156
Epoch: 95184 - Loss: 2551.4468257507847
Epoch: 95185 - Loss: 2551.439842877642
Epoch: 95186 - Loss: 2551.432860155358
Epoch: 95187 - Loss: 2551.4258775839317
Epoch: 95188 - Loss: 2551.4188951633673
Epoch: 95189 - Loss: 2551.4119128936595
Epoch: 95190 - Loss: 2551.404930774794
Epoch: 95191 - Loss: 2551.397948806781
Epoch: 95192 - Loss: 2551.3909669896047
Epoch: 95193 - Loss: 2551.3839853232716
Epoch: 95194 - Loss: 2551.3770038077805
Epoch: 95195 - Loss: 2551.370022443116
Epoch: 95196 - Loss: 2551.363041229271
Epoch: 95197 - Loss: 2551.3560601662452
Epoch: 95198 - Loss: 2551.349079254039
Epoch: 95199 - Loss: 2551.3420984926424
Epoch: 95200 - Loss: 2551.3351178820617
Epoch: 95201 - Loss: 2551.328137422289
Epoch: 95202 - Loss: 2551.321157113318
Epoch: 95203 - Loss: 2551.3141769551407
Epoch: 95204 - Loss: 2551.30719694775
Epoch: 95205 - Loss: 2551.3002170911495
Epoch: 95206 - Loss: 2551.2932373853464
Epoch: 95207 - Loss: 2551.2862578303143
Epoch: 95208 - Loss: 2551.279278426062
Epoch: 95209 - Loss: 2551.2722991725773
Epoch: 95210 - Loss: 2551.265320069862
Epoch: 95211 - Loss: 2551.258341117909
Epoch: 95212 - Loss: 2551.251362316721
Epoch: 95213 - Loss: 2551.2443836662846
Epoch: 95214 - Loss: 2551.2374051666097
Epoch: 95215 - Loss: 2551.2304268176717
Epoch: 95216 - Loss: 2551.223448619482
Epoch: 95217 - Loss: 2551.216470572033
Epoch: 95218 - Loss: 2551.2094926753166
Epoch: 95219 - Loss: 2551.2025149293318
Epoch: 95220 - Loss: 2551.1955373340775
Epoch: 95221 - Loss: 2551.188559889546
Epoch: 95222 - Loss: 2551.181582595731
Epoch: 95223 - Loss: 2551.1746054526275
Epoch: 95224 - Loss: 2551.167628460242
Epoch: 95225 - Loss: 2551.1606516185616
Epoch: 95226 - Loss: 2551.153674927578
Epoch: 95227 - Loss: 2551.1466983873006
Epoch: 95228 - Loss: 2551.139721997713
Epoch: 95229 - Loss: 2551.1327457588236
Epoch: 95230 - Loss: 2551.125769670614
Epoch: 95231 - Loss: 2551.118793733079
Epoch: 95232 - Loss: 2551.111817946225
Epoch: 95233 - Loss: 2551.1048423100597
Epoch: 95234 - Loss: 2551.097866824555
Epoch: 95235 - Loss: 2551.0908914897127
Epoch: 95236 - Loss: 2551.0839163055302
Epoch: 95237 - Loss: 2551.0769412720174
Epoch: 95238 - Loss: 2551.069966389146
Epoch: 95239 - Loss: 2551.0629916569314
Epoch: 95240 - Loss: 2551.056017075351
Epoch: 95241 - Loss: 2551.0490426444208
Epoch: 95242 - Loss: 2551.042068364128
Epoch: 95243 - Loss: 2551.0350942344644
Epoch: 95244 - Loss: 2551.0281202554356
Epoch: 95245 - Loss: 2551.0211464270333
Epoch: 95246 - Loss: 2551.0141727492364
Epoch: 95247 - Loss: 2551.007199222082
Epoch: 95248 - Loss: 2551.000225845512
Epoch: 95249 - Loss: 2550.993252619565
Epoch: 95250 - Loss: 2550.98627954422
Epoch: 95251 - Loss: 2550.979306619476
Epoch: 95252 - Loss: 2550.9723338453286
Epoch: 95253 - Loss: 2550.9653612217758
Epoch: 95254 - Loss: 2550.958388748795
Epoch: 95255 - Loss: 2550.951416426413
Epoch: 95256 - Loss: 2550.9444442546087
Epoch: 95257 - Loss: 2550.937472233377
Epoch: 95258 - Loss: 2550.930500362718
Epoch: 95259 - Loss: 2550.9235286426265
Epoch: 95260 - Loss: 2550.9165570731043
Epoch: 95261 - Loss: 2550.9095856541294
Epoch: 95262 - Loss: 2550.9026143857204
Epoch: 95263 - Loss: 2550.895643267859
Epoch: 95264 - Loss: 2550.888672300534
Epoch: 95265 - Loss: 2550.8817014837587
Epoch: 95266 - Loss: 2550.874730817538
Epoch: 95267 - Loss: 2550.867760301826
Epoch: 95268 - Loss: 2550.8607899366725
Epoch: 95269 - Loss: 2550.853819722026
Epoch: 95270 - Loss: 2550.84684965791
Epoch: 95271 - Loss: 2550.8398797443115
Epoch: 95272 - Loss: 2550.832909981214
Epoch: 95273 - Loss: 2550.8259403686384
Epoch: 95274 - Loss: 2550.818970906565
Epoch: 95275 - Loss: 2550.8120015949976
Epoch: 95276 - Loss: 2550.8050324339333
Epoch: 95277 - Loss: 2550.7980634233463
Epoch: 95278 - Loss: 2550.791094563266
Epoch: 95279 - Loss: 2550.784125853661
Epoch: 95280 - Loss: 2550.7771572945385
Epoch: 95281 - Loss: 2550.7701888858933
Epoch: 95282 - Loss: 2550.7632206277312
Epoch: 95283 - Loss: 2550.7562525200233
Epoch: 95284 - Loss: 2550.7492845627794
Epoch: 95285 - Loss: 2550.7423167560128
Epoch: 95286 - Loss: 2550.7353490996925
Epoch: 95287 - Loss: 2550.728381593821
Epoch: 95288 - Loss: 2550.721414238405
Epoch: 95289 - Loss: 2550.714447033436
Epoch: 95290 - Loss: 2550.707479978902
Epoch: 95291 - Loss: 2550.7005130748107
Epoch: 95292 - Loss: 2550.693546321138
Epoch: 95293 - Loss: 2550.686579717908
Epoch: 95294 - Loss: 2550.6796132650916
Epoch: 95295 - Loss: 2550.6726469627124
Epoch: 95296 - Loss: 2550.6656808107286
Epoch: 95297 - Loss: 2550.6587148091667
Epoch: 95298 - Loss: 2550.6517489580083
Epoch: 95299 - Loss: 2550.644783257257
Epoch: 95300 - Loss: 2550.637817706914
Epoch: 95301 - Loss: 2550.6308523069556
Epoch: 95302 - Loss: 2550.6238870573893
Epoch: 95303 - Loss: 2550.6169219582143
Epoch: 95304 - Loss: 2550.6099570094166
Epoch: 95305 - Loss: 2550.6029922109974
Epoch: 95306 - Loss: 2550.5960275629486
Epoch: 95307 - Loss: 2550.589063065281
Epoch: 95308 - Loss: 2550.5820987179836
Epoch: 95309 - Loss: 2550.5751345210447
Epoch: 95310 - Loss: 2550.5681704744597
Epoch: 95311 - Loss: 2550.561206578249
Epoch: 95312 - Loss: 2550.554242832365
Epoch: 95313 - Loss: 2550.5472792368364
Epoch: 95314 - Loss: 2550.540315791642
Epoch: 95315 - Loss: 2550.533352496792
Epoch: 95316 - Loss: 2550.526389352276
Epoch: 95317 - Loss: 2550.5194263580865
Epoch: 95318 - Loss: 2550.512463514236
Epoch: 95319 - Loss: 2550.505500820693
Epoch: 95320 - Loss: 2550.4985382774803
Epoch: 95321 - Loss: 2550.491575884572
Epoch: 95322 - Loss: 2550.4846136419906
Epoch: 95323 - Loss: 2550.4776515496974
Epoch: 95324 - Loss: 2550.4706896077028
Epoch: 95325 - Loss: 2550.463727816009
Epoch: 95326 - Loss: 2550.4567661746064
Epoch: 95327 - Loss: 2550.4498046835038
Epoch: 95328 - Loss: 2550.442843342679
Epoch: 95329 - Loss: 2550.4358821521364
Epoch: 95330 - Loss: 2550.4289211118835
Epoch: 95331 - Loss: 2550.4219602218777
Epoch: 95332 - Loss: 2550.4149994821514
Epoch: 95333 - Loss: 2550.408038892693
Epoch: 95334 - Loss: 2550.401078453492
Epoch: 95335 - Loss: 2550.3941181645537
Epoch: 95336 - Loss: 2550.387158025866
Epoch: 95337 - Loss: 2550.3801980374283
Epoch: 95338 - Loss: 2550.3732381992236
Epoch: 95339 - Loss: 2550.366278511264
Epoch: 95340 - Loss: 2550.3593189735407
Epoch: 95341 - Loss: 2550.3523595860574
Epoch: 95342 - Loss: 2550.345400348793
Epoch: 95343 - Loss: 2550.3384412617697
Epoch: 95344 - Loss: 2550.3314823249475
Epoch: 95345 - Loss: 2550.3245235383292
Epoch: 95346 - Loss: 2550.3175649019436
Epoch: 95347 - Loss: 2550.310606415761
Epoch: 95348 - Loss: 2550.303648079784
Epoch: 95349 - Loss: 2550.296689894011
Epoch: 95350 - Loss: 2550.28973185842
Epoch: 95351 - Loss: 2550.2827739730214
Epoch: 95352 - Loss: 2550.275816237829
Epoch: 95353 - Loss: 2550.2688586527966
Epoch: 95354 - Loss: 2550.26190121795
Epoch: 95355 - Loss: 2550.25494393328
Epoch: 95356 - Loss: 2550.247986798783
Epoch: 95357 - Loss: 2550.2410298144464
Epoch: 95358 - Loss: 2550.23407298028
Epoch: 95359 - Loss: 2550.227116296272
Epoch: 95360 - Loss: 2550.220159762406
Epoch: 95361 - Loss: 2550.2132033787066
Epoch: 95362 - Loss: 2550.206247145143
Epoch: 95363 - Loss: 2550.199291061725
Epoch: 95364 - Loss: 2550.192335128444
Epoch: 95365 - Loss: 2550.185379345297
Epoch: 95366 - Loss: 2550.1784237122897
Epoch: 95367 - Loss: 2550.171468229397
Epoch: 95368 - Loss: 2550.164512896629
Epoch: 95369 - Loss: 2550.157557713969
Epoch: 95370 - Loss: 2550.1506026814263
Epoch: 95371 - Loss: 2550.1436477990087
Epoch: 95372 - Loss: 2550.136693066678
Epoch: 95373 - Loss: 2550.129738484464
Epoch: 95374 - Loss: 2550.122784052336
Epoch: 95375 - Loss: 2550.115829770314
Epoch: 95376 - Loss: 2550.1088756383656
Epoch: 95377 - Loss: 2550.101921656517
Epoch: 95378 - Loss: 2550.094967824733
Epoch: 95379 - Loss: 2550.0880141430307
Epoch: 95380 - Loss: 2550.0810606114137
Epoch: 95381 - Loss: 2550.074107229859
Epoch: 95382 - Loss: 2550.0671539983623
Epoch: 95383 - Loss: 2550.0602009169265
Epoch: 95384 - Loss: 2550.053247985561
Epoch: 95385 - Loss: 2550.0462952042312
Epoch: 95386 - Loss: 2550.0393425729617
Epoch: 95387 - Loss: 2550.032390091728
Epoch: 95388 - Loss: 2550.025437760532
Epoch: 95389 - Loss: 2550.0184855793773
Epoch: 95390 - Loss: 2550.011533548269
Epoch: 95391 - Loss: 2550.0045816671695
Epoch: 95392 - Loss: 2549.9976299360956
Epoch: 95393 - Loss: 2549.9906783550427
Epoch: 95394 - Loss: 2549.9837269240056
Epoch: 95395 - Loss: 2549.9767756429865
Epoch: 95396 - Loss: 2549.969824511974
Epoch: 95397 - Loss: 2549.9628735309543
Epoch: 95398 - Loss: 2549.955922699945
Epoch: 95399 - Loss: 2549.9489720189295
Epoch: 95400 - Loss: 2549.9420214878987
Epoch: 95401 - Loss: 2549.935071106863
Epoch: 95402 - Loss: 2549.928120875803
Epoch: 95403 - Loss: 2549.9211707947316
Epoch: 95404 - Loss: 2549.9142208636295
Epoch: 95405 - Loss: 2549.9072710824958
Epoch: 95406 - Loss: 2549.90032145133
Epoch: 95407 - Loss: 2549.8933719701276
Epoch: 95408 - Loss: 2549.886422638889
Epoch: 95409 - Loss: 2549.879473457594
Epoch: 95410 - Loss: 2549.872524426265
Epoch: 95411 - Loss: 2549.8655755448667
Epoch: 95412 - Loss: 2549.85862681342
Epoch: 95413 - Loss: 2549.8516782319084
Epoch: 95414 - Loss: 2549.84472980034
Epoch: 95415 - Loss: 2549.837781518688
Epoch: 95416 - Loss: 2549.8308333869663
Epoch: 95417 - Loss: 2549.8238854051638
Epoch: 95418 - Loss: 2549.81693757328
Epoch: 95419 - Loss: 2549.809989891317
Epoch: 95420 - Loss: 2549.803042359264
Epoch: 95421 - Loss: 2549.7960949771154
Epoch: 95422 - Loss: 2549.789147744863
Epoch: 95423 - Loss: 2549.782200662508
Epoch: 95424 - Loss: 2549.7752537300466
Epoch: 95425 - Loss: 2549.768306947478
Epoch: 95426 - Loss: 2549.7613603147884
Epoch: 95427 - Loss: 2549.754413831994
Epoch: 95428 - Loss: 2549.74746749906
Epoch: 95429 - Loss: 2549.7405213160096
Epoch: 95430 - Loss: 2549.7335752828258
Epoch: 95431 - Loss: 2549.7266293995067
Epoch: 95432 - Loss: 2549.7196836660482
Epoch: 95433 - Loss: 2549.7127380824577
Epoch: 95434 - Loss: 2549.705792648701
Epoch: 95435 - Loss: 2549.6988473648025
Epoch: 95436 - Loss: 2549.6919022307497
Epoch: 95437 - Loss: 2549.6849572465285
Epoch: 95438 - Loss: 2549.678012412152
Epoch: 95439 - Loss: 2549.671067727608
Epoch: 95440 - Loss: 2549.664123192885
Epoch: 95441 - Loss: 2549.6571788079937
Epoch: 95442 - Loss: 2549.6502345729186
Epoch: 95443 - Loss: 2549.643290487666
Epoch: 95444 - Loss: 2549.636346552217
Epoch: 95445 - Loss: 2549.629402766587
Epoch: 95446 - Loss: 2549.622459130748
Epoch: 95447 - Loss: 2549.6155156447194
Epoch: 95448 - Loss: 2549.6085723084775
Epoch: 95449 - Loss: 2549.6016291220335
Epoch: 95450 - Loss: 2549.5946860853737
Epoch: 95451 - Loss: 2549.587743198496
Epoch: 95452 - Loss: 2549.580800461402
Epoch: 95453 - Loss: 2549.5738578740775
Epoch: 95454 - Loss: 2549.5669154365264
Epoch: 95455 - Loss: 2549.5599731487496
Epoch: 95456 - Loss: 2549.5530310107333
Epoch: 95457 - Loss: 2549.546089022468
Epoch: 95458 - Loss: 2549.5391471839675
Epoch: 95459 - Loss: 2549.5322054952103
Epoch: 95460 - Loss: 2549.5252639562127
Epoch: 95461 - Loss: 2549.5183225669393
Epoch: 95462 - Loss: 2549.5113813274165
Epoch: 95463 - Loss: 2549.504440237625
Epoch: 95464 - Loss: 2549.4974992975613
Epoch: 95465 - Loss: 2549.4905585072406
Epoch: 95466 - Loss: 2549.483617866622
Epoch: 95467 - Loss: 2549.476677375731
Epoch: 95468 - Loss: 2549.469737034555
Epoch: 95469 - Loss: 2549.4627968430896
Epoch: 95470 - Loss: 2549.455856801332
Epoch: 95471 - Loss: 2549.448916909269
Epoch: 95472 - Loss: 2549.4419771669013
Epoch: 95473 - Loss: 2549.4350375742347
Epoch: 95474 - Loss: 2549.428098131265
Epoch: 95475 - Loss: 2549.4211588379703
Epoch: 95476 - Loss: 2549.4142196943612
Epoch: 95477 - Loss: 2549.4072807004322
Epoch: 95478 - Loss: 2549.400341856165
Epoch: 95479 - Loss: 2549.3934031615827
Epoch: 95480 - Loss: 2549.3864646166626
Epoch: 95481 - Loss: 2549.3795262214035
Epoch: 95482 - Loss: 2549.372587975793
Epoch: 95483 - Loss: 2549.3656498798405
Epoch: 95484 - Loss: 2549.35871193354
Epoch: 95485 - Loss: 2549.3517741368883
Epoch: 95486 - Loss: 2549.3448364898773
Epoch: 95487 - Loss: 2549.3378989924936
Epoch: 95488 - Loss: 2549.330961644746
Epoch: 95489 - Loss: 2549.3240244466338
Epoch: 95490 - Loss: 2549.317087398139
Epoch: 95491 - Loss: 2549.310150499262
Epoch: 95492 - Loss: 2549.303213750022
Epoch: 95493 - Loss: 2549.296277150385
Epoch: 95494 - Loss: 2549.2893407003485
Epoch: 95495 - Loss: 2549.2824043999194
Epoch: 95496 - Loss: 2549.2754682490954
Epoch: 95497 - Loss: 2549.2685322478665
Epoch: 95498 - Loss: 2549.2615963962276
Epoch: 95499 - Loss: 2549.254660694177
Epoch: 95500 - Loss: 2549.247725141714
Epoch: 95501 - Loss: 2549.2407897388266
Epoch: 95502 - Loss: 2549.2338544855215
Epoch: 95503 - Loss: 2549.226919381781
Epoch: 95504 - Loss: 2549.219984427611

{'loss': 3853.4392716049415,
 'weight': array([-4.19374816e-01, -3.01244918e+00, -4.21594840e-01, -5.03198016e+00,
        -7.59860511e-01, -3.26200559e-01,  6.99057114e-01, -1.35913415e+00,
        -2.07706513e+00, -5.03498673e-01,  1.34311737e+00, -2.48102339e-01,
        -2.06675791e-01, -1.91260830e-01,  5.77245091e-01,  2.58276894e-02,
        -6.77741180e-01,  6.03289986e-01,  6.22696077e-01, -8.18350541e-01,
         2.58483671e-01, -1.07240346e+00, -7.37143762e-02,  9.71759404e-01,
         1.16020969e+00, -4.95725003e-01,  9.37019885e-01,  2.28921746e-01,
         1.10810622e-01, -2.50442086e-01, -7.79763840e-01, -1.06926007e+00,
        -2.36921843e+00, -1.70730490e+00, -1.58985507e+00,  2.56164810e-01,
        -3.86633206e-01,  4.31087025e-01,  3.68813026e-01, -3.03464641e+00,
        -3.95584467e-01, -7.65253543e-01, -1.78648164e+00, -5.33296867e-01,
         3.47014462e-01, -1.45918260e+00,  6.69481607e-01,  7.10532099e-01,
        -3.77801282e-01,  5.00357161e-01,  4.07856593e-03, -2.26691859e-01,
        -2.24049357e-01, -2.58684341e+00, -5.92123841e-01,  1.28046035e+00,
        -3.77529793e-02, -1.53964469e+00,  8.89717567e-01, -4.30663253e-01,
        -1.13918452e-01,  1.00929636e+00, -7.98365135e-01,  1.70368536e+00,
        -6.16746543e-01,  1.25487912e+00, -1.26115555e+00,  1.08780324e+00,
         2.82819489e-01, -3.96565589e-01, -5.86930483e-01,  3.10222830e-01,
         4.50669516e-02, -8.13688280e-02,  9.10481662e-01, -2.02003597e-02,
        -2.21690322e+00,  5.35681886e-01, -1.16020914e+00, -1.89361130e+00,
         1.14018075e+00,  7.64701825e-01,  6.83265171e-01,  1.83069734e+00,
        -3.89610312e-01, -4.05980888e-01, -2.11249337e-01,  7.60765630e-02,
        -1.99901565e+00,  5.99572724e-01,  1.19064507e+00])}

In [46]:
preds = poly_model.predict(X_train)
r2score(preds, y_train)

0.9795043552105771